### ISSUE TITLE
Transaction Group support for LogicSig signed transactions

### ISSUE THREAD

**Issue by k3karthic-bleumi** [algorand/js-algorand-sdk#100]
Making a transaction group where one or more of the transactions are signed by a LogicSig does not work. 

The 'signLogicSigTransaction' function internally creates a transaction object from a transaction dictionary and returns the txID & encoded blob. However, the Transaction class constructor does not support passing the groupID as a parameter and sets the internal group parameter to undefined as can be seen in the code below.

https://github.com/algorand/js-algorand-sdk/blob/3ba7463223aab24f67cffb30748679502a4f8d1a/src/transaction.js#L82

This causes the encoded transaction to fail with the error 'empty txgroup' when submitted to the network.

To workaround this issue, we import the internal 'src/transaction.js' & 'src/encoding/encoding.js' modules and reimplement the 'signLogicSigTransaction' function to ensure the groupID is set on the transaction object.

**Comment by EvanJRichard** [comment]
PRs are in progress to fix! Thanks a million again for noting this. :+1:
