### ISSUE TITLE
Expose LogicSig.fromByte

### ISSUE THREAD

**Issue by k3karthic-bleumi** [algorand/js-algorand-sdk#101]
We can create and serialize a LogicSig object using the 'makeLogicSig' method,

```
// create LogicSig object and sign with our secret key
let program = Uint8Array.from([1, 32, 1, 0, 34]);  // int 0 => never transfer money
let lsig = algosdk.makeLogicSig(program);
lsig.sign(keys.secretKey);

assert lsig.verify(sender_pk);

console.log(lsig.toByte()); // Serialized LogicSig
```

However, the deserialization method 'fromByte' is declared as a static method as can be seen in the code below.

https://github.com/algorand/js-algorand-sdk/blob/3ba7463223aab24f67cffb30748679502a4f8d1a/src/logicsig.js#L150

As the LogicSig class is not exposed on the algosdk module, we had to import the internal 'src/logicsig.js' module. Could we have this class or the fromByte method exposed on the algosdk object?

**Comment by EvanJRichard** [comment]
Fix PR in progress! :+1:
