### ISSUE TITLE
Transaction Group support for ASA Transfers

### ISSUE THREAD

**Issue by k3karthic-bleumi** [algorand/js-algorand-sdk#108]
The _'get_obj_for_encoding'_ method on the Transaction class does not seem to set the _'grp'_ parameter for ASA transfers. This causes a transaction group to fail with the error message _'TransactionPool.Remember: transactionGroup: [0] had zero Group but was submitted in a group of 2'_.

I had to monkey patch the method to get it to work,
```
for (let mp of txns) {
    let orig = mp.get_obj_for_encoding;
    let replace = function() {
        let obj = orig.bind(this)();
        obj.grp = this.group;
        return obj;
    };
    mp.get_obj_for_encoding = replace.bind(mp);
}
```

**Comment by EvanJRichard** [comment]
Fix PR in progress! :+1:
