### ISSUE TITLE
can't encode an object with an undefined value 

### ISSUE THREAD

**Issue by JasonWeathersby** [algorand/js-algorand-sdk#113]
let transaction2 = algosdk.makePaymentTxn(myAccountB.addr, 
			myAccountA.addr, params.minFee, 200000, undefined, 
			params.lastRound, params.lastRound + 1000, new Uint8Array(0), 
			params.genesishashb64, params.genesisID);

algosdk.encodeObj(transaction2) fails because of the undefined value.

**Comment by EvanJRichard** [comment]
To encode the object, first use `transaction2.get_obj_for_encoding`
```
       let txn = algosdk.makePaymentTxn(addr,
                addr, fee, 200000, undefined,
                firstRound, lastRound, undefined,
                genesisHash, genesisID);
            let bytes = algosdk.encodeObj(txn.get_obj_for_encoding());
```

**Comment by jasonpaulos** [comment]
Closing because this appears to be resolved.
