### ISSUE TITLE
allow KMD to accept addresses and not public keys

### ISSUE THREAD

**Issue by wisthsb1519** [algorand/js-algorand-sdk#115]
for example, importMultisig() takes in a public key which forces you to decode an address
https://github.com/algorand/js-algorand-sdk/blob/adb082e1944cf0bea4a29163d33d5195cb7fa953/src/client/kmd.js#L297
python works nicely where it takes in an msig object to import a multisig account into a kmd wallet

https://github.com/algorand/py-algorand-sdk/blob/b079db660ae92d0dbf24dc04f28eb722711e426f/algosdk/kmd.py#L353

**Comment by algorotem** [comment]
algorand/java-algorand-sdk#96
