### ISSUE TITLE
JS max integer values

### ISSUE THREAD

**Issue by jciruolo** [algorand/js-algorand-sdk#130]
I'm writing a client validation library for sanitizing user input for this SDK and ran into an edge case that I believe is worth a mention here. 

When trying to set the maximum number of assets that you're allowed to issue to `18446744073709551616`, javascript hits its max integer value, which rounds and loses precision.

Basically,
```javascript
parseInt('18446744073709551616')  // returns 18446744073709552000
```

The traditional way I understand to get around this is to convert to `BigInt` instead, but if this SDK is intended for browser use it will also need to be packaged with a polyfill to handle some less capable browsers. If this SDK is also using the standard Number type it could cause downstream issues from a conversion like this. 

Happy to help how I can, but i'd love your feedback to see if i'm missing something obvious.

**Comment by rotemh** [comment]
Great point and thanks for bringing it up. The SDK is "aware" of this problem. In fact, it will throw an error when you try to use a number that is larger than `MAX_SAFE_INTEGER` (`2^53-1`). When we designed it back then, the assumption was that no transaction can practically have such a large number of Algos so it's ok to not support it. But, that was pre assets time. 

As for the solution, the one you suggested is on point. We would overload the functions to accept also numbers as strings and represent them, as you mentioned,  as BigInt internally. (or to accept BigInt directly).

**Comment by roccomuso** [comment]
`bn.js` package is the approach used by other crypto libs (supported on both node/browser).
