### ISSUE TITLE
public ALGO node

### ISSUE THREAD

**Issue by roccomuso** [algorand/js-algorand-sdk#131]
Is there any public ALGO node with a free token that can bu used for tests?

**Comment by tgmichel** [comment]
@roccomuso for local development you can use [Algorand Sandbox](https://medium.com/algorand/introducing-sandbox-the-quick-way-to-get-started-on-algorand-8082c2d18854).

The service runs on a container, in `4001` port of your localhost. The token is just `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`.

**Comment by Priegle** [comment]
you can also use this service https://www.purestake.com/technology/algorand-api/
