### ISSUE TITLE
Empty blocks can't be accessed

### ISSUE THREAD

**Issue by purestaketdb** [algorand/js-algorand-sdk#16]
I have a piece of JS that goes out and gets the latest block # then retrieves the contents. The last few weeks there has been scripts keeping a constant flow of txns in each block but today it stopped and I'm unable to get anything about a block. 

The code:
`async function getLatest() {
    try {
        let latest = (await algodclient.status()).lastRound;
        let temp = (await algodclient.block(latest));
        console.log(temp.round)
    }
    catch (e) {
        console.log(e)
    }
}`

The error:
`TypeError: Cannot read property 'length' of undefined
    at Algod.block (/Users/tdb/node_modules/algosdk/src/client/algod.js:163:57)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)`

The error is in this function, where it expects a value for txn array length:

`    /**
     * block gets the block info for the given round This call blocks
     * @param roundNumber
     * @returns {Promise<*>}
     */
    this.block = async function (roundNumber) {
        if (!Number.isInteger(roundNumber)) throw Error("roundNumber should be an integer");
        let res = await c.get("/v1/block/" + roundNumber);
        if (res.statusCode === 200) {
          for(var i = 0; i < **res.body.txns.transactions.length**; i++) {
            res.body.txns.transactions[i] = noteb64ToNote(res.body.txns.transactions[i]);
          }
        }
        return res.body;
    };`

**Comment by JasonWeathersby** [comment]
did you update your version? Line 162 looks like this now
        if (res.statusCode === 200 && res.body.txns.transactions !== undefined) {

**Comment by purestaketdb** [comment]
You are correct, I hadn't updated - this is not an issue in the current SDK.
