### ISSUE TITLE
Questions about handling fees

### ISSUE THREAD

**Issue by HebeBlock** [algorand/js-algorand-sdk#164]
During the use process, I found that the handling fee is very high every time. Is there any way to solve it?

![image](https://user-images.githubusercontent.com/39998387/83260537-8e4d3600-a1ec-11ea-823c-fca9929419e0.png)

The handling fee will increase here，What if I want to keep the handling fee to a minimum of 0.001?

![image](https://user-images.githubusercontent.com/39998387/83260574-9c9b5200-a1ec-11ea-84ed-6a15d499b626.png)

**Comment by JasonWeathersby** [comment]
Read this tutorial: https://developer.algorand.org/tutorials/setting-transaction-fee-javascript/ 
There will be changes to this code based on V2 implementation but this code gives you the idea.
