### ISSUE TITLE
Algod v2 API - client.js - HTTPClient method Get - wrong Accept

### ISSUE THREAD

**Issue by purestaketdb** [algorand/js-algorand-sdk#173]
In Algod v2 API several endpoints accept a parameter to return results as msgpack (binary). In the JS SDK for those endpoints they request this by default (which, IMO they should not). 

Issue: In client.js, in the HTTPClient function, get method, the header 'Accept' is set to 'application/json', regardless of the actual expected request. 

```javascript    
this.get = async function (path, query, requestHeaders={}) {
        try {
            return await request
                .get(this.address + path)
                .set(this.token)
                .set(this.defaultHeaders)
                .set(requestHeaders)
                .set('Accept', 'application/json')
                .query(removeEmpty(query));
        } catch (e) {
            throw e;
        }
    };
```

This should either be set to `*/*` or set depending on the expected result, i.e. `application/mspack` when that is the desired response. 

Leaving it as `application/json` for msgpack requests causes issues with AWS API Gateway and results in the SDK not functioning for all calls defaulted to msgpack.

**Comment by purestaketdb** [comment]
For reference - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html - "If contentHandling isn't defined, and if the Content-Type header of the response and the Accept header of the original request match an entry of the binaryMediaTypes list, API Gateway passes through the body. This occurs when the Content-Type header and the Accept header are the same. Otherwise, API Gateway converts the response body to the type specified in the Accept header."

**Comment by purestaketdb** [comment]
Possible fix - https://github.com/algorand/js-algorand-sdk/pull/177

**Comment by ian-algorand** [comment]
Prioritizing this for the upcoming sprint. Thanks for the linked PR
