### ISSUE TITLE
Payment TX expects receiver field to be valid.

### ISSUE THREAD

**Issue by mxmauro** [algorand/js-algorand-sdk#175]
Hi,

`Transaction.from_obj_for_encoding` expects a valid `rcv` field on payment txs but the function must accept an undefined receive, The same might apply on asset transfer txs.

Reason: Close transactions does not require a valid receiver and, actually, the node also accepts txs with undefined receivers (the result of this is the funds are transferred to the zero account)

Regards,
Mauro.

**Comment by algorotem** [comment]
Hi Mauro, 
thanks for bringing it up. `Transaction.from_obj_for_encoding` is an internal function. Do you have an example of where it fails using one of the external ones?

**Comment by ian-algorand** [comment]
@mxmauro we're going to close this issue since we can't figure out how to replicate this failure. If you add more information, feel free to reopen. Thanks!
