### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Invertisment** [algorand/js-algorand-sdk#204]
I'd like to know whether there is going to be any effort to provide typings for this SDK.
I've tried to use `dts-gen` to create a type for the SDK but it doesn't add much info.
It would be nice to have typings to use the SDK with TS without needing to read everything from the docs.

This is what the `dts-gen` generates:
```
  /** Declaration file generated by dts-gen */
  export class Algod {
    constructor(token: string, baseServer: string, port: number, headers?: object);
    status(): Promise<NodeStatus>;
  }

  export class Algodv2 {
    constructor(token: string, baseServer: string, port: number, headers?: object);
    status(): Action<any>;
  }

  interface Account {
    addr: string;
    sk: Uint8Array
  }

  export function Indexer(...args: any[]): any;
  export function Kmd(token: any, baseServer: any, port: any): any;
  <...>
```
I omitted many more static methods but the pattern is that most of them return `any` as the type instead of having a specific object.
Also `Algodv2` doesn't have any methods. It would be nice to have types there.

**Comment by algorotem** [comment]
Hi Invertisment, 

Many thanks for the ides, it's a great one! Unfortunately, we currently don't have any plans to add typescript support. But we will definitely consider that in the future. If you happened to add it yourself, please don't hesitate to open a PR. We always welcome new contributions.

**Comment by Invertisment** [comment]
I'm not sure if I want to make a PR right now as our typings are not complete.
We add things as we go and it already has some things in there but it's far from complete as we didn't use everything.

You may want to check our code out: https://github.com/scale-it/algorand-builder/blob/master/packages/types-algosdk/index.d.ts
