### ISSUE TITLE
Grouped transactions failing with “empty txgroup” when signed using signLogicSigTransactionObject

### ISSUE THREAD

**Issue by algodesk-io** [algorand/js-algorand-sdk#208]
I'm trying to group the transactions and one of the transactions is signed using logic signature.

1. Transaction 1 (signed using private key)
2. Transaction 2 (signed using LogicSig)

If i Group these transactions, then it is failing with “empty txgroup” error.
This issue is reproducible only when one of the grouped transactions is signed using LogicSig.

rawSignedTxn = sdk.signLogicSigTransactionObject(unsignedTransaction, lsig);

The workaround for this is:

rawSignedTxn = sdk.signLogicSigTransactionObject(unsignedTransaction, lsig).blob;

**Comment by EvanJRichard** [comment]
Hi, @algodesk-io, thanks for reporting this! Can you please supply a minimal code snippet reproducing the problem, so I can see how `computeGroupID` etc are used? Thanks again!
