### ISSUE TITLE
[Found work] Msgpack responses are undefined in browsers

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/js-algorand-sdk#209]
@JasonWeathersby found that he could do operations like v2 `getBlock` and `pendingTransactionInformation` in node, but in a webapp the response would come back as `undefined`. Further investigation by @jasonpaulos found that this was likely due to how the superagent works: https://visionmedia.github.io/superagent/#parsing-response-bodies . Suggested solution from @winder and @jasonpaulos is to move `encoding.decode(res.body)` (from `do()` for the operations in question) into one of the `request.parse[application/msgp]` handlers mentioned in the link.

**Comment by jasonpaulos** [comment]
Actually it turns out we need to add `.responseType('arraybuffer')` to requests that return binary data to get superagent to pass along the ArrayBuffer directly. Putting up a PR now.

**Comment by jasonpaulos** [comment]
Reopened because this is still an issue: in the browser superagent returns an ArrayBuffer but in Node it returns a Buffer. Therefore this still breaks in the browser since ArrayBuffers don't have `.length`.
