### ISSUE TITLE
Don't silently change the fee

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/js-algorand-sdk#224]
Currently the transaction constructor silent changes the few when it is less than the minimal txn fee. This silently causes transactions to be authorized for more than is expected. It would be better for the transaction to be submitted with the lower fee and then rejected, so we could surface the error to the approver.

https://github.com/algorand/js-algorand-sdk/blob/c789ba84ab4de299544219fc7f5a13b23049dc1c/src/transaction.js#L133

This would be alleviate if the suggested parameters api call included an accurate fee value, but it doesn't.

**Comment by algorotem** [comment]
Hi @jeapostrophe,
Thanks for this comment as well. 

This was a design choice. We found that users prefer this way than the other but happy to (and will) revisit the assumption again. 
Moreover, I'll make sure it's clear in the documentation that this is the case.  

Best
