### ISSUE TITLE
Expose consensus parameters

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/js-algorand-sdk#225]
This library should have a way to define current consensus parameters. In particular, I need to know the minimum balance so I can initialize new accounts properly. My JS code shouldn't have `100000` hardcoded.

**Comment by algorotem** [comment]
Hi @jeapostrophe, thanks for the comment. 

The SDK was designed to enable offline use cases and therefore some of the information cannot be retrieved online and needs to be hardcoded (Mainly when it's being updated rarely).

That being said, I think exposing the parameters in a more convenient way is a good idea and we will look into adding another API point for that matter. 

Best,
Rotem

**Comment by ian-algorand** [comment]
Sounds like the scope of this issue will be an API endpoint that exposes the consensus params.

**Comment by algoanne** [comment]
this is covered by https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2148 so closing this one.
