### ISSUE TITLE
Enhancement: Include signed transaction display method 

### ISSUE THREAD

**Issue by purestaketdb** [algorand/js-algorand-sdk#239]
After creating a transaction and signing it, in order to view the result, the developer has to know how to reverse all the encodings. It would be helpful for there to be two things to make it easier. 

1. A helper function to view/access the signed transaction directly without knowing the decoding steps for a given field 

2. Compatibility between the V2 transactions and goal, so `goal clerk inspect` will work properly.

**Comment by EvanJRichard** [comment]
@purestaketdb Good idea, going to make separate tickets for `1.` and `2.` shortly

**Comment by EvanJRichard** [comment]
@purestaketdb We'll be working out of the child tickets, closing this parent ticket to avoid duplication.
