### ISSUE TITLE
Catch undefined param note (which is optional)

### ISSUE THREAD

**Issue by Slobish** [algorand/js-algorand-sdk#25]
SDK standards show that param **note** in a transaction object is optional. Nevertheless, you must explicitly define that is an empty Uint8Array.

I made a pull-request but close it right away because I am not sure whether my fix is right or not. Uint8Array might not need a 0 in its declaration.
https://github.com/algorand/js-algorand-sdk/pull/24

Here Go-algosdk shows how param **note** is manipulated as an optional param. 
https://github.com/algorand/go-algorand-sdk#manipulating-multisig-transactions

**Comment by JasonWeathersby** [comment]
I think the actual error is on line 55 of the transaction: "note": Buffer.from(this.note),
We need to check whether it is undefined.
https://github.com/algorand/js-algorand-sdk/blob/master/src/transaction.js#L55

**Comment by rotemh** [comment]
Yes, the fix is proper. Will be merged in the next version.
