### ISSUE TITLE
Large app state integers are rounded

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/js-algorand-sdk#251]
## Summary
When an app has a number larger than Javascript's max safe integer, such as 79999999999999973, stored as a value in app state, the goal app read will output:

```
      "reserve": {
        "tt": 2,
        "ui": 79999999999999973
}
```

But calling `javascriptAlgosdkClient.accountInformation(account.addr).do()` to get the same app's state will return a rounded value of 79999999999999970.

## Scope
We'll need to put together a reproduction of this issue to see where the problem is. I suspect it's because `JSON.parse` will round any values greater than 2^53-1. If that's the case, the requests we send for any endpoint that returns app state should be encoded in msgpack, since that encoding can handle 64 bit ints.

## Urgency
This affects smart contracts that are already deployed. Should fix ASAP.

**Comment by ian-algorand** [comment]
If the account info endpoint doesn't let you request the info in messagepack, then the estimate on this will grow. @jasonpaulos to update appropriately
