### ISSUE TITLE
[React] appendSignMultisigTransaction error: Arguments must be Buffers

### ISSUE THREAD

**Issue by giocasu** [algorand/js-algorand-sdk#252]
Hi, I'm trying to build a simple app with ReactJS with multisig functionalities. 
I'm encountering this error when using appendSignMultisigTransaction method.

`index.js:337 Uncaught (in promise) TypeError: Arguments must be Buffers
    at Function.compare (0.chunk.js:18745)
    at 0.chunk.js:11552
    at Array.map (<anonymous>)
    at Object.mergeMultisigTransactions (0.chunk.js:11545)
    at mergeMultisigTransactions (0.chunk.js:10163)
    at Object.appendSignMultisigTransaction (0.chunk.js:10152)
    at test (main.chunk.js:376)
`

The following code works in node but not when called in my ReactJS app.
```javascript
async function test() {
  // from https://github.com/PureStake/algosigner-dapp-example/tree/master/nodeJs/multisig
  let account1 = algosdk.generateAccount();
  let account2 = algosdk.generateAccount();
  let account3 = algosdk.generateAccount();
  const mparams = {
    version: 1,
    threshold: 2,
    addrs: [
      account1.addr,
      account2.addr,
      account3.addr,
    ],
  };
  let multsigAddr = algosdk.multisigAddress(mparams);
  let comboAddresses = {
    "account1": {
      "addr": account1.addr,
      "sk": account1.sk.toString(),
      "mno": algosdk.secretKeyToMnemonic(account1.sk)
    },
    "account2": {
      "addr": account2.addr,
      "sk": account2.sk.toString(),
      "mno": algosdk.secretKeyToMnemonic(account2.sk)
    },
    "account3": {
      "addr": account3.addr,
      "sk": account3.sk.toString(),
      "mno": algosdk.secretKeyToMnemonic(account3.sk)
    },
    "multisigAddr": multsigAddr,
    "mparams": {
      version: 1,
      threshold: 2,
      addrs: [
        account1.addr,
        account2.addr,
        account3.addr,
      ],
    }
  }
  let algodclient = new algosdk.Algodv2({ "X-API-Key": "YOUR_API_KEY" },
    "YOUR_URL",
    '');
  let params = await algodclient.getTransactionParams().do();
  let txn = {
    "from": multsigAddr,
    "to": "YOUR_ADDRESS",
    "fee": params.fee,
    "amount": Math.floor((Math.random() * 1000) + 1),
    "firstRound": params.firstRound,
    "lastRound": params.lastRound,
    "genesisID": params.genesisID,
    "genesisHash": params.genesisHash,
    "note": new Uint8Array(0)
  };
  let rawSignedTxn = algosdk.signMultisigTransaction(txn, comboAddresses.mparams, Uint8Array.from(comboAddresses.account1.sk.split(','))).blob;
  let directsig = algosdk.appendSignMultisigTransaction(rawSignedTxn, comboAddresses.mparams, Uint8Array.from(comboAddresses.account2.sk.split(','))).blob;
  // BLAH BLAH
}
```
The exception is raised by

https://github.com/algorand/js-algorand-sdk/blob/7d5db3e4338b562ea06323f6ecad70def8eee6cb/src/multisig.js#L149

and it goes away if ```compare``` arguments are passed to ```Buffer.from```

**Comment by jasonpaulos** [comment]
@giocasu thanks for reporting this! We will fix it soon.

**Comment by jasonpaulos** [comment]
I think the latest version of algosdk (v1.8.1) may have fixed this problem. Could you let me know if the error still happens with this version, and if so which browser you are using?

**Comment by giocasu** [comment]
Hi, thanks for the replies, 
I still got the error with latest algosdk version. I am using Chrome  v. 87.0.4280.88 on Windows 10, but it does not work in Firefox 83.0 too.

**Comment by jasonpaulos** [comment]
@giocasu thanks for the response. I've confirmed that this issue only happens when using React specifically--running this code in a browser without React works fine. If you run `npm ls buffer` in the directory of a React app that has algosdk installed, you can see why:

```
$ npm ls buffer
react-js-test@0.1.0 /Users/jason/Workspace/react-js-test
├─┬ algosdk@1.8.1
│ └── buffer@6.0.3 
└─┬ react-scripts@4.0.1
  └─┬ webpack@4.44.2
    └─┬ node-libs-browser@2.2.1
      └── buffer@4.9.2
```

It looks like the react-scripts build process forces version 4.9.2 of the `buffer` package to be used everywhere, even if another package (like ours) specifies a different version of `buffer` as a dependency. Later versions of `buffer` allow `Buffer.compare` to work with Buffers and Uint8Arrays, but 4.9.2 does not.

I will think about how to address this problem.

**Comment by jasonpaulos** [comment]
@giocasu I just merged a PR which converts the arguments to Buffers before calling `Buffer.compare`. This seems like the best solution for now.
