### ISSUE TITLE
Examples needs to be updated to V2

### ISSUE THREAD

**Issue by rfustino** [algorand/js-algorand-sdk#254]
## Summary
Most of the examples in this repo are outdated and need to be updated to V2. This includes the documentation in the readme and the sample web app.

## Scope
We should update the entire set of examples similarly to what has already happened to the python sdk: https://github.com/algorand/py-algorand-sdk/tree/develop/examples.

Some sections that the examples should cover:
* Using the transaction note field
* Creating/sending group transactions
* Using multisigs
* Creating LogicSigs and signing transactions with them
* Specific asset transactions (create, freeze, clawback, etc.)
* Specific app transactions (create, opt in, call, etc.)

## Urgency/Relative priority
We're showing incorrect information on the documentation, it's something we should change asap. Could result in bad states for users.

**Comment by rfustino** [comment]
Keep install instructions, but can we just remove these examples and just point to the developer site?  https://developer.algorand.org/docs/build-apps/hello_world/ . I will make a separate issue to update the webapp sample to use V2 and potentially indexer.

**Comment by jasonpaulos** [comment]
I think the right balance here is to direct users to the developer site's quick start code, but still provide examples and documentation for JS-specific features and patterns.
