### ISSUE TITLE
Algodv2 - versionsCheck Issue

### ISSUE THREAD

**Issue by k3karthic-bleumi** [algorand/js-algorand-sdk#256]
Unable to run versionsCheck using Algodv2 due to the code below. The await should be on "this.c" and not "c".

https://github.com/algorand/js-algorand-sdk/blob/7d5db3e4338b562ea06323f6ecad70def8eee6cb/src/client/v2/algod/versions.js#L12

The following error is returned when using Algosdk v1.8.1

![image](https://user-images.githubusercontent.com/50232871/101631205-fe653000-3a49-11eb-9873-f544873fe3bf.png)

**Comment by jasonpaulos** [comment]
@k3karthic-bleumi thanks for reporting this! I will get it fixed ASAP.
