### ISSUE TITLE
makeApplicationCreateTxn says approvalProgram is not a Uint8Array when it is

### ISSUE THREAD

**Issue by logiclogue** [algorand/js-algorand-sdk#264]
makeApplicationCreateTxn says approvalProgram is not a Uint8Array when it is

I'm having an issue with this line:

https://github.com/algorand/js-algorand-sdk/blob/263fd5dd3fd65a38c4c82fd06504ba7795be70fe/src/transaction.js#L70

If I do `approvalProgram instanceof Uint8Array` it's `true`, but `approvalProgram.constructor === Uint8Array` is `false`.

Can someone point me in the right direction or is this a permanent issue with the library?

**Comment by logiclogue** [comment]
I'm able to temporarily get around the issue with `approvalProgram.constructor = Uint8Array;`, but I shouldn't have to do that

**Comment by jasonpaulos** [comment]
Are you sure your approval program is a Uint8Array, not a Buffer or some other subclass? Checking the constructor is a pretty common way to verify that the object is a Uint8Array.

**Comment by logiclogue** [comment]
Yep it turned out to be a Buffer. Chrome dev tools was pretty printing it as a Uint8Array for some reason, which is what confused me. Thanks for the quick reply and apologies for the confusion
