### ISSUE TITLE
Begin migration to TypeScript

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/js-algorand-sdk#295]
## Summary
This SDK is currently written in plain JavaScript and we do not provide any TypeScript definitions. It's time to fix this!

## Scope
It will most likely be difficult to migrate the entire library to TypeScript, so let's focus on the commonly used, public parts first, such as the makeTxn functions, Transaction class, and the encoding/decoding functions. After this the Algodv2 class would probably be next, but this will be more difficult because we'll have to also annotate every possible REST API response.

In general we need to:
* Incorporate TypeScript compilation into this package's build steps.
* Add types to files one-by-one, focussing on commonly used user-facing classes/functions first.
* Ensure the compiled JS files and type definitions are included when the package is published.

The TypeScript docs provide some guidance about how to migrate a repo: https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

## Urgency
Many users have requested TypeScript support (#204, #245, #265) since it would greatly improve the usability of our library and catch some bugs a lot sooner.

**Comment by damassi** [comment]
I was just about to post a new issue asking if there's interest in this! Wonderful 👍

**Comment by jasonpaulos** [comment]
@jdtzmn is currently working on this on the `jacob/typescript-migration` branch.
