### ISSUE TITLE
Migrate Logic templates to TypeScript

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/js-algorand-sdk#307]
## Summary
This issue tracks the migration of the logic templates to TypeScript.

## Scope
Migrate the directory `src/logicTemplates` to TypeScript.

## Urgency
Lower priority since the logic templates do not get used as much as other parts of the SDK.

**Comment by JacobMGEvans** [comment]
Greetings,
If you are interested we can "Raid" your repository, there would be one big PR from our Organization, for a large specific task/problem domain; in this case TS conversion.

We would need a maintainer as a point of contact, we prefer using Discord https://discord.gg/xkdkAJZsBR

Let me know if you are interested.
You can read more about what we are doing here: https://github.com/OpenSourceRaidGuild/tutorial-quest
This is also an example of how we work and the workflow: HospitalRun/hospitalrun-frontend#2516

cc: @nobrayner @mpeyper @Aprillion

**Comment by jasonpaulos** [comment]
Hi @JacobMGEvans, thank you for the offer, but we have already converted most of the codebase to TypeScript so I don't think a "raid" is necessary.

If you (or any other community member) would like to submit a PR solving this specific issue, that would be appreciated.

**Comment by JacobMGEvans** [comment]
No worries, thank you for the response! Feel free to check us out regardless 😄

**Comment by beakersoft** [comment]
Hi, i'm going to pick this up and have a look at it, kinda new with typescript put I've experience with javascript so I'm going to use it as a learning exercise

**Comment by lorenzoram** [comment]
Do you still need help with this?

**Comment by jasonpaulos** [comment]
Actually the logic templates will be deprecated soon, so there may not be much point to migrating them to TypeScript.
