### ISSUE TITLE
Lazy-load `langspec.json` to save space on the 32KB JSON file

### ISSUE THREAD

**Issue by jdtzmn** [algorand/js-algorand-sdk#316]
Importing `langspec.json` in its entirety immediately adds 32kb to the webpack bundle. Ideally, we should dynamically import the JSON file only when it is needed. Refer to the [webpack docs ](https://webpack.js.org/guides/lazy-loading/) for more details and possible implementation examples.

**Comment by Eric-Warehime** [comment]
`langspec.json` was removed entirely in https://github.com/algorand/js-algorand-sdk/pull/632
