### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by atrefonas** [algorand/js-algorand-sdk#327]
Hello, 

It says "For detailed information about the different API calls in client, visit https://developer.algorand.org". However, when I go there, I can't find the documentation about the API calls. In fact one page says to go to this Github to see the documentation. Could you please clarify?

**Comment by JasonWeathersby** [comment]
The developer site lists features of Algorand. Within each of these guides are complete examples written in the four SDK languages Algorand supports. For example creating an Asset is shown here: https://developer.algorand.org/docs/features/asa/#creating-an-asset

**Comment by atrefonas** [comment]
Makes sense, thanks!
