### ISSUE TITLE
sign transaction in react-native

### ISSUE THREAD

**Issue by AmazingBeerBelly** [algorand/js-algorand-sdk#33]
Hi,

  I have developed algorand wallet in react-native, and I find I can't sign the transaction in ios simulator. I find the problem is Buffer.from(). I run the test code in the node env and I can send the transaction. I have compared the transaction's blob and find the node's transaction's blob is different from the react-native's transaction's blob. How should I solve this problem?

thanks a lot.

**Comment by JasonWeathersby** [comment]
can you post a sample of the code where this failing?

**Comment by AmazingBeerBelly** [comment]
async sendTx(mnemonic, amount, toAddr) {
    const algodclient = new algosdk.Algod(token, server, port)
    const recoveredAccount = algosdk.mnemonicToSecretKey(mnemonic)
    const params = await algodclient.getTransactionParams()
    const endRound = params.lastRound + parseInt(1000, 10)
    const txn = {
      from: recoveredAccount.addr,
      to: toAddr,
      fee: 1000,
      amount,
      firstRound: params.lastRound,
      lastRound: endRound,
      genesisID: params.genesisID,
      genesisHash: params.genesishashb64,
      note: new Uint8Array(0),
    }
    const signedTxn = algosdk.signTransaction(txn, recoveredAccount.sk)
    // signedTxn.blob's length is 247 in node, and 767 in react native.
    // I have found result of the Buffer.from() is different.
    const tx = (await algodclient.sendRawTransaction(signedTxn.blob))
    return tx
  },

**Comment by AmazingBeerBelly** [comment]
And I have an error when generating an account. 

code:
const account = algosdk.generateAccount()

then it reports errors "[Error: no PRNG]"

**Comment by JasonWeathersby** [comment]
I believe this is an issue with Native React's lack of support for Crypto https://github.com/facebook/react-native/issues/22933 . This is not a model we support currently

**Comment by AmazingBeerBelly** [comment]
Ok, I will follow the react native issue. Thank you very much.
