### ISSUE TITLE
Documentation instructions are an infinite loop.

### ISSUE THREAD

**Issue by tidux** [algorand/js-algorand-sdk#330]
The README says to check https://developer.algorand.org/ for more information, but https://developer.algorand.org/docs/reference/sdks/#javascript says to check the github repository.  Which is it?

**Comment by JasonWeathersby** [comment]
We definitely need to clean up the dev site link here. The description of how to use the js sdk is on every page that showcases an Algorand Feature. For example, building an Atomic Transfer shows JS examples here: https://developer.algorand.org/docs/features/atomic_transfers/#step-by-step-guide
