### ISSUE TITLE
(1.9.0) ReactJS: TypeError: algosdk__WEBPACK_IMPORTED_MODULE_3___default.a.Algodv2 is not a constructor 

### ISSUE THREAD

**Issue by giocasu** [algorand/js-algorand-sdk#352]
Hi, client instantation (1.9.0)

```
let algodclient = new algosdk.Algodv2({ "X-API-Key": "YOUR_API_KEY" },
        "YOUR_SERVER",
        '');
```
crashes with TypeError: algosdk__WEBPACK_IMPORTED_MODULE_3___default.a.Algodv2 is not a constructor
in a typescript react app

npx create-react-app myapp --template typescript

```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import algosdk from 'algosdk'
function App() {
 let algodclient = new algosdk.Algodv2({ "X-API-Key": "YOUR_API_KEY" },
        "YOUR_SERVER",
        '');
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**Comment by jasonpaulos** [comment]
Thanks for reporting this, we are working on a solution.

**Comment by jasonpaulos** [comment]
@giocasu we have a potential fix, and I've created a dev version of the library to test. Could you verify that this works for you?

Steps to test:
1. Remove algosdk from your project (`npm uninstall --save algosdk`)
2. Download the dev version [algosdk-1.9.1-dev.tgz.zip](https://github.com/algorand/js-algorand-sdk/files/6386828/algosdk-1.9.1-dev.tgz.zip)
3. Unzip the file (should be named `algosdk-1.9.1-dev.tgz`)
4. Install dev algosdk with `npm install --save path/to/algosdk-1.9.0-dev.tgz`
5. Build your project and see if the error is fixed.

**Comment by giocasu** [comment]
Hi, the client instantation went good but if I add
this line 
 ```
algodclient.getTransactionParams().do().then((params: any) => {
    console.log(params);
  });
```
it crashes again: 
Unhandled Rejection (TypeError): path__WEBPACK_IMPORTED_MODULE_0___default.a.posix is undefined

complete code:
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import algosdk from 'algosdk'
function App() {
 let algodclient = new algosdk.Algodv2({ "X-API-Key": "YOUR_API_KEY" },
        "YOUR_SERVER",
        '');
algodclient.getTransactionParams().do().then((params: any) => {
    console.log(params);
  });
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**Comment by jasonpaulos** [comment]
@giocasu thank you for finding that issue too. We are looking for a solution.

**Comment by jasonpaulos** [comment]
@giocasu I think we've fixed it now. Can you verify with this build: [algosdk-1.9.1-dev.2.tgz.zip](https://github.com/algorand/js-algorand-sdk/files/6393303/algosdk-1.9.1-dev.2.tgz.zip)?

**Comment by giocasu** [comment]
@jasonpaulos It's working now, thank you very much.

**Comment by jasonpaulos** [comment]
Great, we will release this as 1.9.1 soon.
