### ISSUE TITLE
1.9.0 Typescript Error on build

### ISSUE THREAD

**Issue by meltie1** [algorand/js-algorand-sdk#354]
`/tmp/build/node_modules/algosdk/dist/types/src/logicsig.d.ts`
       TypeScript error in /tmp/build/node_modules/algosdk/dist/types/src/logicsig.d.ts(45,75):
       ',' expected.  TS1005

       43 |     appendToMultisig(secretKey: Uint8Array): void;
       44 |     signProgram(secretKey: Uint8Array): Uint8Array;
45 |     singleSignMultisig(secretKey: Uint8Array, msig: EncodedMultisig): [sig: Uint8Array, index: number];
       |                                                                           ^
       46 |     toByte(): Uint8Array;
       47 |     static fromByte(encoded: ArrayLike<any>): LogicSig;
       48 | }

**Comment by jasonpaulos** [comment]
Is this the output of `npm run build`? Also, can you let me know the output of running `npm ls`?

**Comment by itslesther** [comment]
Same issue when running "tsc" typescript command

**Comment by itslesther** [comment]
Upgrading to typescript 4.2.4 worked for me

**Comment by jasonpaulos** [comment]
Thanks for letting me know. We support TypeScript version 4.2 and above. I'll add this to the README to make it more clear.
