### ISSUE TITLE
Type Error in Asset Creation method

### ISSUE THREAD

**Issue by atz3n** [algorand/js-algorand-sdk#358]
Hi,

there seems to be a type error for the `makeAssetCreateTxnWithSuggestedParamsFromObject(params)` function parameter in TypeScript. It requires the `manager`, `freeze`, `clawback` and `reserve` fields. 

Due to the [docs](https://developer.algorand.org/docs/features/asa/) these fields are optional and can be set to `""` to disable the functionality. However, setting the parameters to an empty string leads to the following error:
```
Error: address seems to be malformed
```

As a workaround cast the parameter type to 'any' ->`makeAssetCreateTxnWithSuggestedParamsFromObject(<any> params)`

**Comment by jasonpaulos** [comment]
@atz3n thanks for reporting this. For this SDK, the correct way to disable these accounts is by passing in `undefined`, not an empty string.

Additionally, @jdtzmn has created a PR to allow these fields to be optional, so in the future you can just omit the fields you wish to disable.
