### ISSUE TITLE
Allow 'null' args for makeLogicSig

### ISSUE THREAD

**Issue by atrefonas** [algorand/js-algorand-sdk#365]
It seems makeLogicSig was changed to where it only checks undefined args, although it used to check for null args. For backwards compatibility purposes it should be checking both. 

For example this code fails from the makeLogicSig line returning null, due to the null args. The source code should still compile even if the args are null. The current workaround of course is to change it to undefined.

The fix is that makeLogicSig should accept both undefined and null args, and still compile the source code even with null/undefined args.
```

        let compilation = await compileProgram(algodClient, program);
        let uintAr = _base64ToArrayBuffer(compilation.result);
        let args = null;
        let lsig = algosdk.makeLogicSig(uintAr, args);
        console.log("lsig addr: " + lsig.address());
```
        
The issue happens here: https://github.com/algorand/js-algorand-sdk/blob/fd187cedab70cb123333ba62ca3e6fe98c1e7d3d/src/logicsig.ts#L25

```


let args: Uint8Array[] | undefined;    
if (typeof bufferOrUint8ArrArgs !== 'undefined')      
args = bufferOrUint8ArrArgs.map((arg) => new Uint8Array(arg));


```

**Comment by jasonpaulos** [comment]
Good point. If anyone wants to make a PR for this, I'd be happy to review it.
