### ISSUE TITLE
Cannot sign a transaction from Jest's node environment 

### ISSUE THREAD

**Issue by jdtzmn** [algorand/js-algorand-sdk#367]
## Summary

Since the internal `bytesToSign` function returns a `Buffer` instead of a `Uint8Array`, signing a transaction throws an error inside Jest's node testing environment.

### Background

Jest's standard node environment contains globals that cause a `Buffer` instance check against `Uint8Array` to fail. Therefore, the following statement will print `false` in a Jest environment but `true` in a standard node environment.

```js
const u = new Buffer([1, 2, 3, 4]);
console.log(u instanceof Uint8Array)
```

## Scope

Change the `bytesToSign` implementation so that it returns a `Uint8Array` instead of a `Buffer` instance and double check that signing transactions is then possible in the Jest environment.

## Urgency

This bug prevents users from testing any transaction signing operations from within the Jest testing framework.

**Comment by algochoi** [comment]
Closed by this PR https://github.com/algorand/js-algorand-sdk/pull/801
We now use a `Uint8Array` for this:
https://github.com/algorand/js-algorand-sdk/pull/801/files#diff-fff0ee1c855d7fdef5ec027268d27066a50d0c0dc4e4832b51f8a2e40129e177R1116
