### ISSUE TITLE
DryRunResponse for stateful NoOp call

### ISSUE THREAD

**Issue by ratik21** [algorand/js-algorand-sdk#373]
I am trying to produce a `DryRunRequest` and get it's response. I followed the [tutorial](https://developer.algorand.org/docs/features/asc1/debugging/#using-dryrun-for-debugging-a-teal-program) for lsig, which works fine, but having an issue with the same for stateful call (`NoOp`) request.

### Steps
```js
const tx = algosdk.makeApplicationNoOpTxn(..);
const app = algodClient.getApplicationByID(app_id).do(); // deployed stateful application id
const dr = new algosdk.modelsv2.DryrunRequest({
  apps: [ app ]
  txns: [{ txn: tx }],
  sources: undefined
}):
const resp = await algodClient.dryrun(dr).do();
```
here is the response:
```
{
  "error": "",
  "protocol-version": "https://github.com/algorandfoundation/specs/tree/ac2255d586c4474d4ebcf3809acccb59b7ef34ff",
  "txns": [
    {
      "app-call-messages": [
        "ApprovalProgram",
        "REJECT",
        "logic eval error: program version 65 greater than max supported version 3"
      ],
      "app-call-trace": [
        {
          "error": "program version 65 greater than max supported version 3",
          "line": 0,
          "pc": 0,
          "stack": []
        }
      ],
      "disassembly": null
    }
  ]
}
```
Here are the smart contracts:
- *approval.teal*
  ```
  #pragma version 3
  
  int NoOp
  txn OnCompletion
  ==

  bnz application_call

  int 1
  return

  application_call:

  // read global state
  byte "counter"
  dup
  app_global_get

  // increment the value
  int 1
  +

  // store to scratch space
  dup
  store 0

  // update global state
  app_global_put

  // load return value as approval
  load 0
  return
  ```
  
- *clear.teal*
  ```
  #pragma version 3
  int 1
  return
  ```

**Comment by ratik21** [comment]
Question:

in the tutorial we are creating an SDK transaction object (using `makePaymentTr..`) - [https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L86](https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L86), but when i check this [test](https://github.com/algorand/js-algorand-sdk/blob/develop/tests/7.AlgoSDK.js#L948), we just pass a simple transaction object ( `tx = { fee: 1000, fv: ..}` ) to `DryRunRequest`.

**Comment by jasonpaulos** [comment]
@ratik21 this will be fixed by #399.

> Question:
>
> in the tutorial we are creating an SDK transaction object (using makePaymentTr..) - https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L86, but when i check this test, we just pass a simple transaction object ( tx = { fee: 1000, fv: ..} ) to DryRunRequest.

I believe both inputs (a `Tranasction` class instance and a raw transaction object) are acceptable, though I'd recommend you use `Transaction` instances returned by one of the transaction maker functions.

**Comment by ratik21** [comment]
@jasonpaulos i am still getting the same response (`program version 65 greater than max supported version 3`). I tested using the latest commit on `develop`.

I am doing the same steps mentioned in my original comment. Am i doing anything wrong here? If you want i can give you an executable script producing the response as mentioned above.

**Comment by jasonpaulos** [comment]
Yes, please provide a small executable script that shows this this issue and I can take a look. Reopening because this may not be fixed.

**Comment by ratik21** [comment]
@jasonpaulos attached folder will teal code & an executable script. Please update the mnemonic to your private-net master. You can run `npx ts-node debug.js` to run the script. I have attached dryrun response and the msgp dump from my system as well. Please let me know if that works.

[dryrun-stateful.zip](https://github.com/algorand/js-algorand-sdk/files/6819160/dryrun-stateful.zip)

**Comment by jasonpaulos** [comment]
The issue here is the same one described in https://github.com/algorand/js-algorand-sdk/issues/374#issuecomment-886888387
