### ISSUE TITLE
`EncodedSignedTransaction` is missing `msig` field

### ISSUE THREAD

**Issue by amityadav0** [algorand/js-algorand-sdk#389]
`EncodedSignedTransaction` should have `msig`, because while decoding transaction using algosdk.decodeSignedTransaction(stxn); `msig is lost`

**Comment by jasonpaulos** [comment]
This appears to be just a type issue, meaning if you call `algosdk.decodeSignedTransaction` with a multisig transaction, it will have an `msig` property but TypeScript doesn't think it does. @amityadav0 let me know if this is not the case.

Also, the `lsig` field is also missing.

**Comment by amityadav0** [comment]
yes, this is the case. it's a type issue

**Comment by jasonpaulos** [comment]
Closed by #401.
