### ISSUE TITLE
Multiple TS errors

### ISSUE THREAD

**Issue by Lumene98** [algorand/js-algorand-sdk#390]
![image](https://user-images.githubusercontent.com/26761348/123303744-6b3fa380-d51e-11eb-8641-ffc8f3cc8baa.png)
During build

**Comment by jdtzmn** [comment]
Can you tell me what your environment is (webpack/react app/typescript compiler/etc.)? And what version of TypeScript are you using?

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 can you tell me what your environment is (webpack/react app/typescript compiler/etc.)? And what version of TypeScript are you using?

I'm working on aws-cdk(in typescript) and using typescript 3.9.7(ts-node 9.0.0)

**Comment by Lumene98** [comment]
Even trying older versions of algosdk doesn't fix the error, @jdtzmn did you find anything?

**Comment by jdtzmn** [comment]
Yes, I apologize for the delayed response. This package requires TypeScript version 4.2 or greater. The errors you are receiving are caused by TypeScript syntax added in versions after 3.9.7. Please let me know if updating TypeScript to 4.2 solves your issues.

**Comment by Lumene98** [comment]
> Yes, I apologize for the delayed response. This package requires TypeScript version 4.2 or greater. The errors you are receiving are caused by TypeScript syntax added in versions after 3.9.7. Please let me know if updating TypeScript to 4.2 solves your issues.

Thanks now it works just fine hopefully cdk updates the typescript version soon
