### ISSUE TITLE
cannot set manager, reserve, freeze, clawback addresses to blank string `''`

### ISSUE THREAD

**Issue by amityadav0** [algorand/js-algorand-sdk#394]
Before `types` update if we wanted to set  manager, reserve, freeze fields to blank using sdk, we passed 
`let ctxn = algosdk.makeAssetConfigTxnWithSuggestedParams(recoveredAccount2.addr, note, 
        assetID, manager, reserve, freeze, clawback, params, false);`
we used the extra strictEmptyAddressChecking parameter in the config change function and set fields to `undefined`.

But after types update we cannot set any fields to undefined, and if we use a blank string, we get error `address seemed to be malformed`.
![0x1](https://user-images.githubusercontent.com/26249903/123593620-5ad44500-d80c-11eb-83b7-a0a2153e0706.png)

**Comment by jdtzmn** [comment]
Why can't you set fields to undefined after the types update? I was unable to reproduce type issues locally - the following code yielded no type errors.

```js
makeAssetConfigTxnWithSuggestedParams('', null, 1, undefined, undefined, undefined, undefined, undefined)
```

**Comment by amityadav0** [comment]
i am trying to set these fields in `.ts` file, This is the error i am getting `Argument of type 'undefined' is not assignable to parameter of type 'string'.`, i checked the types as well, they accept `string` only.
It works when trying from a `.js` file because types are not used here.

**Comment by jdtzmn** [comment]
The code included above was also from a `.ts` file and the error did not seem to appear. I'll try to reproduce the issue with a different TypeScript config.

**Comment by jdtzmn** [comment]
In a completely fresh project with algosdk version 1.10.0, typescript version 4.3.5, and the following tsconfig.json, I got no warnings and managed to successfully compile.

```json
{
  "compilerOptions": {
    "target": "ES2017",
    "moduleResolution": "node",
    "strictFunctionTypes": true,
    "esModuleInterop": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true
  }
}
```

The `test.ts` file:

```ts
import * as algosdk from 'algosdk'
import { SuggestedParams } from 'algosdk'

algosdk.makeAssetConfigTxnWithSuggestedParams('', undefined, 1, undefined, undefined, undefined, undefined, undefined as unknown as SuggestedParams)
```

**Comment by amityadav0** [comment]
hi, this is our tsconfig
```
"compilerOptions": {
    "target": "ES2020",
    "lib": [
      "esnext",
      "dom"
    ],
    "typeRoots": ["node_modules/@types"],
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowJs": true,
    "module": "commonjs",
    "resolveJsonModule": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "declaration": true
  },
```

**Comment by amityadav0** [comment]
typescript: `4.3.4`, i will try to fix it, with changing config

**Comment by jdtzmn** [comment]
This is very strange. With TypeScript v4.3.4 and your `tsconfig.json` from above, I still received no error messages from the IDE and when compiling. I even tried initializing variables as `undefined` instead of using direct values, exactly as you wrote in your first example, but I still had no luck with it.

@jasonpaulos perhaps you could try reproducing this on your computer?

**Comment by amityadav0** [comment]
Thanks, i was able to solve this with latest commit, probably the problem was with the builds.
