### ISSUE TITLE
types issue with `modelsv2.DryrunRequest`

### ISSUE THREAD

**Issue by ratik21** [algorand/js-algorand-sdk#410]
## Subject

While constructing a [`new algosdk.modelsv2.DryrunRequest({..})`](https://github.com/algorand/js-algorand-sdk/blob/develop/src/client/v2/algod/models/types.ts#L1012) in a typescript project, all parameters are required (apps, accounts, round, timestamp ..etc). However, only `txns` should be required. Please let me know if that's not the case.
```js
export class DryrunRequest extends BaseModel {
  public accounts: Account[]; // should be optional

  public apps: Application[]; // should be optional OR required in case of stateful programs

  public latestTimestamp: number | bigint; // should be optional

  public protocolVersion: string;  // should be optional

  public round: number | bigint;  // should be optional

  public sources: DryrunSource[];  // not sure about this, but should be optional as well

  public txns: EncodedSignedTransaction[]; // this should be required
}
```

##  Steps to reproduce

Running this script in typescript should reproduce the type errors: [https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L132](https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L132)

**Comment by robert-zaremba** [comment]
Ping. Any ETA for this issue?

**Comment by barnjamin** [comment]
@robert-zaremba I filed a PR for this 

https://github.com/algorand/js-algorand-sdk/pull/478
