### ISSUE TITLE
Add WalletConnect `TransactionSigner`

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/js-algorand-sdk#411]
## Summary
[WalletConnect on Algorand](https://developer.algorand.org/docs/get-details/walletconnect/walletconnect-schema/) allows developers to sign transactions using a wallet that supports WalletConnect on Algorand.

Using WalletConnect to sign transactions like this is currently possible, but it could be made easier. This issue is to create a `TransactionSigner` backed by WalletConnect. This signer may be used in the `AtomicTransactionComposer` class in the same way as other signers.

## Scope
* Add the ability to create a `TransactionSigner` backed by WalletConnect.
* Consider how package dependencies should work. There are two solutions as far as I can see:
  * Make the `algosdk` package have an optional peer dependency of `@walletconnect/client` (this is only viable if npm does not automatically install peer dependencies, need to look into this more). This has the disadvantage that a version of `algosdk` will only work with a specific version of `@walletconnect/client`.
  * Create a new "plugin" package that has peer dependencies of `algosdk` and `@walletconnect/client`. This has the advantage that different versions of the plugin can be used to implement compatibility between all versions of `algosdk` and `@walletconnect/client`.

**Comment by Eric-Warehime** [comment]
@jasonpaulos Not sure if we want to add walletconnect as a dep to our SDK. It looks like we have docs in the dev portal now which describe how someone can use the SDK to integrate w/ the wallectconnect protocol.

Do you agree we can close this?

**Comment by jasonpaulos** [comment]
> Not sure if we want to add walletconnect as a dep to our SDK.

As a direct dependency, no, but I outlined some ways we could get around this in the issue description.

> It looks like we have docs in the dev portal now which describe how someone can use the SDK to integrate w/ the wallectconnect protocol.
> 
> Do you agree we can close this?

We do provide guidance for using WalletConnect with this SDK on our docs: https://developer.algorand.org/docs/get-details/walletconnect/. In my opinion it's not a seamless process, and if someone want to use it with the AtomicTransactionComposer, they'll need to build what this issue suggests anyway.

So I think there's still a benefit to adding this feature, but it's certainly lower priority compared to most other things.

If you want to close since we have no immediate plans to work on this, that would make sense though.

**Comment by SilentRhetoric** [comment]
The docs link in the comment above currently 404s.  I assume this is because the old v1 WalletConnect API has since been sunset.

I think this issue has indirectly been resolved by two community libraries that now handle WalletConnect v2 integration:

1. <https://github.com/TxnLab/use-wallet>
2. <https://github.com/SilentRhetoric/solid-algo-wallets>

Therefore, it may be time to close this issue.

**Comment by jasonpaulos** [comment]
A lot has changed since this issue was created, and I agree it no longer makes sense to pursue this feature, so I'll close this.
