### ISSUE TITLE
The extraPages value is lost on decodeUnsignedTransaction()

### ISSUE THREAD

**Issue by PureBrent** [algorand/js-algorand-sdk#418]
### Subject of the issue
In the current version of algosdk at 1.11.0, the from_obj_for_encoding() in algosdk does not include extraPages, however the get_obj_for_encoding() does include building apep from extraPages. 

This results in loss of the field when performing algosdk.decodeUnsignedTransaction() after it has been encoded via algosdk.encodeUnsignedTransaction(). 

### Steps to reproduce
1. Create an application transaction using a make function like makeApplicationCreateTxnFromObject() with extraPages set to 1. 
2. Encode the transaction using encodeUnsignedTransaction(). 
3. Decode the transaction using decodeUnsignedTransaction().

```
var algosdk = require('algosdk');

const arbitraryParams = {
    flatFee: false,
    fee: 0,
    firstRound: 16124012,
    lastRound: 16125012,
    genesisID: 'testnet-v1.0',
    genesisHash: 'SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI='
}

let txn = algosdk.makeApplicationCreateTxnFromObject({
    from: 'GAQVB24XEPYOPBQNJQAE4K3OLNYTRYD65ZKR3OEW5TDOOGL7MDKABXHHTM', 
    numLocalInts: 1, 
    numLocalByteSlices: 1, 
    numGlobalInts: 1,
    numGlobalByteSlices: 0,
    approvalProgram: new Uint8Array("ASABACI=".split("").map(x => x.charCodeAt(0))),

    extraPages: 1,

    suggestedParams: {...arbitraryParams}
});

let enc_txn = algosdk.encodeUnsignedTransaction(txn);
let dec_txn = algosdk.decodeUnsignedTransaction(enc_txn);

console.log(`Before: ${txn['extraPages']}, After: ${dec_txn['extraPages']}`);
```

### Expected behaviour
The extraPages value is retained.

### Actual behaviour
The extraPages value is undefined.

**Comment by jasonpaulos** [comment]
@PureBrent thank you for finding this, we create a PR to fix it

**Comment by jasonpaulos** [comment]
Version 1.11.1 has just been released which fixes this issue
