### ISSUE TITLE
Add ABI encoding support

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/js-algorand-sdk#425]
## Summary
Add support for encoding and decoding ABI values, as described in https://github.com/algorandfoundation/ARCs/pull/7

## Scope
Add ability to:
* Parse and serialize ABI type strings, e.g. `(uint64, byte[], address)`
* Encode and decode ABI values, using type information

**Comment by shiqizng** [comment]
the latest changes are here,  https://github.com/algorand/js-algorand-sdk/tree/abi/encoding/src/abi
I believe the next step is to implement the tests.
