### ISSUE TITLE
Export types in `src/client/client.ts`

### ISSUE THREAD

**Issue by ratik21** [algorand/js-algorand-sdk#437]
We require these types in [`algo-builder`](https://github.com/scale-it/algo-builder)

```js
export interface AlgodTokenHeader {
  'X-Algo-API-Token': string;
}

export interface IndexerTokenHeader {
  'X-Indexer-API-Token': string;
}

export interface KMDTokenHeader {
  'X-KMD-API-Token': string;
}

export interface CustomTokenHeader {
  [headerName: string]: string;
}
```
Can we please export these in index file?

**Comment by Eric-Warehime** [comment]
Opened #772 to resolve this. Let me know if this is still an issue for you and/or feedback you have on that PR. Thanks!
