### ISSUE TITLE
makeAssetTransferTxnWithSuggestedParamsFromObject version on revoke function, executes, but the assets are not revoked

### ISSUE THREAD

**Issue by rfustino** [algorand/js-algorand-sdk#446]
### Subject of the issue

makeAssetTransferTxnWithSuggestedParamsFromObject does not work on a clawback, the assets are left in the holder account that was revoked.

This one however works, (commented out)

makeAssetTransferTxnWithSuggestedParams

### Your environment
line 518 in the attached does not cause an error, asset should be 0. It still has 100.
-->

### Steps to reproduce

1. run the attached code, 
2. When it get to the Asset Clawback step, and displays the asset holder info, the is still 100 in the Bob's account using makeAssetTransferTxnWithSuggestedParamsFromObject and works with makeAssetTransferTxnWithSuggestedParams 

### Expected behaviour
amount is clawedback 
### Actual behaviour
amount is not clawed back
[asaSecurityTokens.js.zip](https://github.com/algorand/js-algorand-sdk/files/7239659/asaSecurityTokens.js.zip)
.

**Comment by jasonpaulos** [comment]
Hi @rfustino, from your attached code:

```javascript
const rtxn = algosdk.makeAssetTransferTxnWithSuggestedParamsFromObject({
    from: sender,
    to: recipient,
    closeRemainderTo,
    assetRevocationTarget: revocationTarget,
    amount,
    note,
    assetIndex: assetID,
    suggestedParams: params,
    reKeyTo
});
```

The mistake is that you are using `assetRevocationTarget` instead of `revocationTarget` as the field name. This should work instead. If not, please reopen the issue.

```javascript
const rtxn = algosdk.makeAssetTransferTxnWithSuggestedParamsFromObject({
    from: sender,
    to: recipient,
    closeRemainderTo,
    revocationTarget,
    amount,
    note,
    assetIndex: assetID,
    suggestedParams: params,
    reKeyTo
});
```
