### ISSUE TITLE
algosdk.Algodv2 overwrites empty port parameter

### ISSUE THREAD

**Issue by tholcman** [algorand/js-algorand-sdk#458]
### Subject of the issue

```
const client = new algosdk.Algodv2("DUMMYTOKEN", "http://127.0.0.1:17458");
```

Should create a client which will request port 17458, but the client requests port 4180. 

it is overwritten here:

https://github.com/algorand/js-algorand-sdk/blob/develop/src/client/v2/algod/algod.ts#L27

### Your environment

SDK version 1.12.0, develop branch, ...

### Steps to reproduce

1. Use an URL with defined non-standard port without `port` parameter
2. ...

### Expected behaviour

It should request a algod on "http://127.0.0.1:17458"

### Actual behaviour

it requests "http://127.0.0.1:4180"

**Comment by winder** [comment]
Closing in favor of #657
