### ISSUE TITLE
writeToFile in both cli and browser contexts

### ISSUE THREAD

**Issue by barnjamin** [algorand/js-algorand-sdk#467]
## Problem

Dump the contents of a transaction group to a file for later evaluation or signing

## Solution

In the browser I wrote a hacky method

```js
export function download_txns(name, txns) {
    let b = new Uint8Array(0);
    for(const txn in txns){
        b = concatTypedArrays(b, txns[txn])
    }
    var blob = new Blob([b], {type: "application/octet-stream"});

    var link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.download = name;
    link.click();
}

export function concatTypedArrays(a, b) { // a, b TypedArray of same type
    var c = new (a.constructor)(a.length + b.length);
    c.set(a, 0);
    c.set(b, a.length);
    return c;
}
```

**Comment by jasonpaulos** [comment]
I don't really see why this should be part of the main library. I think the SDK should definitely make it as easy as possible to encode and decode transactions to raw bytes, at which point the user can choose to write this to a file, or a database, or a QR code, or whatever they want to do with it.

**Comment by barnjamin** [comment]
It seemed reasonable to feature match the py-algorand-sdk `write_to_file` method but I can close this for now
