### ISSUE TITLE
Typo in docs and types

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/js-algorand-sdk#470]
https://algorand.github.io/js-algorand-sdk/modules.html#makeapplicationoptintxn

`foreignAssets?: AppOptInTxn["appForeignApps"],`

should be

`foreignAssets?: AppOptInTxn["appForeignAssets"],`

**Comment by jasonpaulos** [comment]
Thanks for reporting this. It's a pretty benign bug in our typescript definitions since `appForeignApps` and `appForeignAssets` have the same type, but I will get a PR up to fix this.

**Comment by jeapostrophe** [comment]
Thanks!
