### ISSUE TITLE
Invalid type of field amount in response to function accountInformation()

### ISSUE THREAD

**Issue by ma-spadafora** [algorand/js-algorand-sdk#476]
### Subject of the issue
The field `amount` of the elements of the array `assets` returned by `algosdk.Algodv2.accountInformation()` is always a `number`.

### Your environment

* Software version: `3.0.1.dev`
* Operating System details: `sandbox on macOS`

### Steps to reproduce

1. Create an asset with: `total=2^64-1` and retrieve its identifier (`assetId`)
2. Invoke function `accountInformation(reserve_address)` through the sdk.
3. Locate the `asset` element, in the array `assets` of the response, corresponding to `assetId`.

### Expected behaviour
the field `asset.amount` must be of type `bigint` with value `18446744073709551615`.

### Actual behaviour
the field `asset.amount` has type `number` and its value is rounded to `18446744073709552000`.

**Comment by jasonpaulos** [comment]
See my response on your other issue: https://github.com/algorand/js-algorand-sdk/issues/475#issuecomment-985016440
