### ISSUE TITLE
algosdk.signLogicSigTransactionObject does not work

### ISSUE THREAD

**Issue by DedicatedDev** [algorand/js-algorand-sdk#484]
### Your environment
algoSDK: 1.12.0
I'm working on solving this issue right now. I've just knew that this issue happened from algoSDK. 
https://github.com/ulamlabs/OpenNFT/issues/17

Here is screenshot. 
in process, this part crash with this message. 

![image](https://user-images.githubusercontent.com/62229912/145805204-13807358-c4db-40b4-aac0-ee16aabbb6f1.png)

![image](https://user-images.githubusercontent.com/62229912/145805111-edbe2a5d-f7f9-478f-9c4c-8b07f1d5ccff.png)

### Steps to reproduce

1.
2.

**Comment by jasonpaulos** [comment]
What type is `tx.group`? It should be a `Uint8Array` or `Buffer`.

**Comment by DedicatedDev** [comment]
it is buffer right now.

**Comment by jasonpaulos** [comment]
Please post an example of the contents of the `tx.group` buffer.

Additionally, where is the error being thrown?

**Comment by DedicatedDev** [comment]
I've posted this on the discord channel.

**Comment by DedicatedDev** [comment]
![image](https://user-images.githubusercontent.com/62229912/145854453-f84c94a9-e0d5-4933-9d71-b324f3a6249b.png)

**Comment by DedicatedDev** [comment]
![image](https://user-images.githubusercontent.com/62229912/145854538-8ef194c6-f6cf-443e-b32b-017d4d8c4226.png)

**Comment by DedicatedDev** [comment]
if that's possible, can we discuss on the algorand javascript sdk channel? I've asked many things to barnji there but did not solve this still.

**Comment by jasonpaulos** [comment]
Closing this because I believe we fixed the problem on discord (wrong input for group ID hash)
