### ISSUE TITLE
Move `/examples` to a new repo called `sdk-examples`

### ISSUE THREAD

**Issue by fionnachan** [algorand/js-algorand-sdk#495]
## Problem
I found out that there's `/examples` in this repo _just now_ and was shocked because I couldn't find the link to these examples on the official docs and have never seen it being shared on discord but they look super useful!

Normally developers would not `git clone` the sdk repo in order to learn how to use the sdk so these examples are just sitting here without making as much impact as they would have.

## Solution
If the examples for all official (or even unofficial) sdks are consolidated under one repo, this one repo can help onboard new devs more easily.

btw from what I see, only [`js-algorand-sdk`](https://github.com/algorand/js-algorand-sdk/tree/develop/examples) and [`py-algorand-sdk`](https://github.com/algorand/py-algorand-sdk/tree/develop/examples) have `/examples`

**Comment by barnjamin** [comment]
I _just_ started to think about how to structure examples across the SDKs. There are a number of things that a lot of people need to implement but maybe don't belong in the main SDK. Things like signature verification for a transaction or parsing block data for example.

I started to spec out what the set of examples might contain here: 
https://github.com/barnjamin/py-algorand-sdk/blob/examples-restructure/examples/README.md
