### ISSUE TITLE
Retrieve storage accounts for an Application

### ISSUE THREAD

**Issue by AwolDes** [algorand/js-algorand-sdk#511]
## Problem

For a given application id, return a list of local storage accounts.

## Solution

This functionality exists in the Python SDK. [When using the indexer to get `accounts`](https://py-algorand-sdk.readthedocs.io/en/latest/algosdk/v2client/indexer.html#algosdk.v2client.indexer.IndexerClient.accounts), you can pass an `application_id` to filter to that application.

## Dependencies

I don't think so - I believe it is functionality that just needs to be built.

## Urgency

Moderate, I guess? It would be very useful for us at https://xbacked.io to retrieve this information for frontends and having a divergence in functionality between SDKs seems strange.

**Comment by fionnachan** [comment]
https://algorand.github.io/js-algorand-sdk/classes/_internal_.SearchAccounts.html

you can get it with
```typescript
const accounts = await indexerClient.searchAccounts().applicationID(123456789).do();
```

**Comment by AwolDes** [comment]
Apologies - I guess I didn't reach the docs thoroughly enough. Thanks @fionnachan!
