### ISSUE TITLE
Algorand SDK with vite

### ISSUE THREAD

**Issue by Zedonboy** [algorand/js-algorand-sdk#513]
The SDK generates browser errors.

```Uncaught ReferenceError: Buffer is not defined```

Is the npm package only used in Nodejs environment?

**Comment by fionnachan** [comment]
It requires buffer to work with encoding / decoding.

To make it work with vite, you will have to install `buffer` and `path-browserify` as dependencies.

In `vite.config.js`, specify:

```js
resolve: {
  alias: {
    path: 'path-browserify';
  }
}
```

In `index.html`, add the following:

```html
<script type="module">
  import { Buffer } from 'buffer';
  window.Buffer = Buffer;
</script>
```

To utilize the Buffer polyfill in production builds, in `vite.config.js`, add:

```js
import inject from '@rollup/plugin-inject';
export default defineConfig({
  ...,
  build: {
    rollupOptions: {
      plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
    },
  },
  ...
});
```

**Comment by Zedonboy** [comment]
Solved my issue, thank you.

**Comment by Alex99y** [comment]
Hello @fionnachan ! Is there a solution for the latest version of [CRA](https://github.com/facebook/create-react-app#readme)?. It uses webpack v5 but it seems that it doesn't allow you to modify the webpack config file without using `npm run eject`.
