### ISSUE TITLE
Not retrieving accurate ASA balance

### ISSUE THREAD

**Issue by cbaunach** [algorand/js-algorand-sdk#522]
### Subject of the issue

From the code and screenshots below I’ve documented how I can view this accounts accurate balance of `18446744073709551615` for tokens `70474481` or `70474529` in algoexplorer but if I try and retrieve that value using the code below, then I get the value as a number like this `18446744073709552000` with reduced precision

code:
```
import algosdk from "algosdk";
var indexer = false

export function useIndexerClient() {
  if (!indexer) {
    const key = "testnet";
    const ALGO_INDEXER_SERVER = "https://algoindexer.testnet.algoexplorerapi.io"
    const ixURL = new URL(ALGO_INDEXER_SERVER);
    indexer = new algosdk.Indexer("", ALGO_INDEXER_SERVER, ixURL.port);
  }

  return indexer;
}

export async function fetchAccount(addr) {
  const Indexer = useIndexerClient();
  const result = await Indexer.lookupAccountByID(addr)
    .do()
    .catch((e) => console.log(e));
  return result.account
}


const accountData = await fetchAccount('IC5DKGRHEHW3GQIQFJFAYSY3NNVJ7P3LVL3W4X4OLISKJ7224Y4LU5HS4M')
console.log(accountData.assets)
```

output of above code:
![Screenshot from 2022-02-16 13-01-10](https://user-images.githubusercontent.com/89322349/154341665-a1dc68d8-8036-4565-8c4a-bd458f6f9a72.png)

account balances for the same ASAs in algoexplorer:
https://testnet.algoexplorer.io/address/IC5DKGRHEHW3GQIQFJFAYSY3NNVJ7P3LVL3W4X4OLISKJ7224Y4LU5HS4M
![Screenshot from 2022-02-16 13-00-51](https://user-images.githubusercontent.com/89322349/154341766-2513ff49-af8e-44f0-81ce-ca85da420279.png)

### Your environment

* Software version: `algosdk 1.13.1`
* Tested in bash cli but any cli will probably work

### Steps to reproduce

1. create new folder
2. run `npm init -y`
3. run `npm i algosdk`
4. add `"type": "module",` to package.json object
5. create `test.js` file and copy code in the subject of this issue into it
6. run `node test.js` in the created folder

### Expected behaviour

Result returns accurate account ASAs balances (or an additional amount field that lists the balance as a string with accurate precision)

### Actual behaviour

Result returns inaccurate balances for account ASAs

**Comment by jasonpaulos** [comment]
You'll need to use the `setIntDecoding` method to indicate how you want the response to treat integers larger than JavaScript's `Number.MAX_SAFE_INTEGER`.

Unfortunately for backwards compatibility, the default option is to return all integers as `number`s, which means large ints are not accurately represented.

You can either set it on an individual request (i.e. `const result = await Indexer.lookupAccountByID(addr).setIntDecoding(algosdk.IntDecoding.BIGINT).do()`) or once on the indexer client to change the default value for all requests from that client.

More info in the docs: https://algorand.github.io/js-algorand-sdk/classes/_internal_.LookupAccountByID.html#setIntDecoding & https://algorand.github.io/js-algorand-sdk/classes/Indexer.html#setIntEncoding

**Comment by cbaunach** [comment]
Alright, that'll work; thanks Jason!
