### ISSUE TITLE
Unable to resolve module crypto from algosdk.min.js

### ISSUE THREAD

**Issue by thangld322** [algorand/js-algorand-sdk#530]
### Unable to resolve module crypto from algosdk.min.js

I'm trying to use algosdk in an Expo-powered React Native app generated from [Ignite](https://github.com/infinitered/ignite). When I run `yarn start`, it has an error as below.

![image](https://user-images.githubusercontent.com/29674139/155978146-877177bd-fa48-4c19-a666-23aede6194a5.png)

### Your environment

* Algod version: 12885032963 3.2.3.stable [rel/stable] (commit #d2289a52)
* Yarn: 1.22.10
* Typescript: ^4.5.5
* Operating System details: Ubuntu 20.04

### Steps to reproduce

1. Generate Expo-powered React Native app from https://github.com/infinitered/ignite
2. yarn add algosdk
3. yarn install
4. yarn start

**Comment by jasonpaulos** [comment]
Unfortunately we have not tested react native support with this SDK. The error you're getting is because a node.js dependency is not present in react native.

You might be able to use a library like [isomorphic-webcrypto](https://www.npmjs.com/package/isomorphic-webcrypto) to satisfy the crypto dependency, but I unfortunately can't give you more help than that because I haven't attempted it. Additionally, you may run into issues if `bigint` is not supported by the JS engines that react native uses.

A similar issue was made and apparently resolved, which might be helpful: https://github.com/algorand/js-algorand-sdk/issues/179

**Comment by thangld322** [comment]
@jasonpaulos Thank for your help.
I have been able to resolve this issue by using `babel-plugin-rewrite-require`
Steps:
- Add these lines to babel.config.js:
```
module.exports = {
  plugins: [
    [require('babel-plugin-rewrite-require'), {
       aliases: {
           crypto: 'crypto-browserify',
           stream: 'readable-stream',
       },
       throwForNonStringLiteral: true
    }],
}
```
- yarn add crypto-browserify
- yarn add readable-stream
- yarn add -D babel-plugin-rewrite-require
Hope this will help new developers when they run into this issue.

***Off topic
How ever when I try this example code:
```typescript
      import * as algosdk from "algosdk"
      const algodToken = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
      const algodServer = 'http://localhost';
      const algodPort = 4001;
      let algodClient = new algosdk.Algodv2(algodToken, algodServer, algodPort);

      (async () => {
        console.log(await algodClient.status().do())
      })().catch((e) => {
        console.log(e)
      })
``` 
It returns this error:
```
Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
at node_modules/algosdk/dist/browser/algosdk.min.js:2:160183 in A.prototype.callback
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:601:4 in setReadyState
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:396:6 in __didCompleteResponse
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:135:10 in EventEmitter#emit
```
Can you help me fix this?
sandbox status:
```
algod - goal node status
Last committed block: 20065243
Time since last block: 3.8s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c
Round for next consensus protocol: 20065244
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: testnet-v1.0
Genesis hash: SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=

indexer - health
Indexer disabled for this configuration.
```

**Comment by tejas-kothari** [comment]
@thangld322 could i contact you via email or Discord? I am facing the same issue, and tried your solution but it didn't work
