### ISSUE TITLE
Fees amount of created transactions are not respected by default.

### ISSUE THREAD

**Issue by jails** [algorand/js-algorand-sdk#537]
### Subject of the issue

Fees amount of created transactions are not respected by default.

### Your environment

* algosdk: 1.14.0
* Ubuntu linux

### Steps to reproduce

```js
import algosdk from 'algosdk';

let transaction = new algosdk.Transaction({
  amount: 150000000,
  fee: 2000,
  firstRound: 19734456,
  lastRound: 19735456,
  from: '<FROM ADDRESS>',
  type: 'pay',
  genesisID: 'mainnet-v1.0',
  genesisHash: 'wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=',
  to: '<TO ADDRESS>'
});

console.log(transaction.fee); // <- show 494000 instead of 2000
```

### Expected behaviour

When a transaction is created with some specified fee, the fee amount should be respected. This **should be** the default behavior.

### Actual behaviour

The fee is increased by 250%

**Comment by barnjamin** [comment]
For the fee to be interpreted as a flat fee, the flat fee flag must be set to true otherwise its interpreted as fee per byte where the byte count is the size of the transaction.

This should do what you expect:
```js
let transaction = new algosdk.Transaction({
        amount: 150000000,
        fee: 1000,
        flatFee: true,
        firstRound: 19734456,
        lastRound: 19735456,
        from: accts[0].addr,
        type: TransactionType.pay,
        genesisID: 'mainnet-v1.0',
        genesisHash: 'wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=',
        to: accts[0].addr
    });
  ```
