### ISSUE TITLE
Program MaxLength is less than go-algorand support

### ISSUE THREAD

**Issue by bo-abstrlabs** [algorand/js-algorand-sdk#543]
### Subject of the issue

I'm trying to deploy a contract, which when compiled into Uint8Array, has 1470 bytes. In go-algorand, there is a limit of 2048 byte contract (if without extra pages), but js-algorand-sdk reject contracts thtat more than 1000 bytes:

https://github.com/algorand/js-algorand-sdk/blob/501599bcb91fb3803de2a563c550c1571cfbf355/src/logic/logic.ts#L31

### Your environment

`develop` branch of js-algorand-sdk. `master` branch of go-algorand, algod.

### Steps to reproduce

I was triggering the deploy from algo builder, but by adding debug console.log I'm able to identify the deploy is rejected by https://github.com/algorand/js-algorand-sdk/blob/501599bcb91fb3803de2a563c550c1571cfbf355/src/logic/logic.ts#L194

### Expected behaviour

Contract, after compiled binary that's below 2048 bytes should be accepted. If an app account has paid extra pages, this size limit should be 2048*pages. Alternatively, have a loose bound at js-algorand-sdk and let algod refuse oversized contracts.

See:
https://developer.algorand.org/docs/get-details/parameter_tables/?from_query=MaxAppProgramCost#smart-contract-constraints
https://github.com/algorand/go-algorand/blob/5a9f94a1b4240b79f48b5736294690790659ef42/config/consensus.go#L1004

### Actual behaviour

Deploy > 1000 byte contract will fail at https://github.com/algorand/js-algorand-sdk/blob/501599bcb91fb3803de2a563c550c1571cfbf355/src/logic/logic.ts#L194

**Comment by jasonpaulos** [comment]
I believe that limit of 1000 is meant to be applied to LogicSig contracts. Ideally any application contracts should not be pre-checked by this code at all, and instead the network should perform validation when the transaction is submitted

**Comment by bo-abstrlabs** [comment]
@jasonpaulos Thanks! You're right. 1000 is the correct upperbound for LogicSig contracts. Isn't a bug
