### ISSUE TITLE
Docs: add enum for possible `exclude` values on indexer docs

### ISSUE THREAD

**Issue by barnjamin** [algorand/js-algorand-sdk#554]
## Problem
Its not immediately clear what values are possible to pass:
https://algorand.github.io/js-algorand-sdk/classes/_internal_.LookupAccountByID.html#exclude

## Solution

Add docs or formalize the enum

**Comment by fionnachan** [comment]
should be resolved now?

**Comment by barnjamin** [comment]
Yes, Thank you!
