### ISSUE TITLE
Tealdbg cannot decode dryrun requests encoded by the SDK when there are assets with total supply larger than 2^53-1

### ISSUE THREAD

**Issue by rlora** [algorand/js-algorand-sdk#555]
### Encoding dryrun requests fail for assets with large supplies

We have an application that automatically generates dryrun requests for transactions that fail. These transactions are later inspected and debugged off-chain.

We noticed that some transactions cannot be unpacked by tealdbg. It issues this error:

```
2022/04/22 20:37:54 Decoding as JSON DryrunRequest object failed: json decode error [pos 1]: only encoded map or array can be decoded into a struct
2022/04/22 20:37:54 Debug error: msgpack decode error [pos 3662]: cannot decode unsigned integer: unrecognized descriptor byte: cb/float
```

We think this failure is related to transactions that refer assets that were created with a large total supply. Using Bigint. i.e. larger than 2^53-1 but smaller than 2^64-1. An example of this kind of asset in the testnet is: https://testnet.algoexplorer.io/asset/81167581

When we unpack the message pack file into JSON we notice that the amounts for these assets are expressed as Floats:
```
"assets": [
  {
    "amount": 9.9999999998E+17,
    "asset-id": 4,
    "is-frozen": false
  },
  {
    "amount": 9980000000,
    "asset-id": 5,
    "is-frozen": false
  }
],
```

This seems consistent with the error **byte: cb/float** but we have not debugged any further.

### Steps to reproduce

1. Create an Asset with a large supply with account A. For example: 10,000,000,000,000,000
2. Make account B and C optin the asset
3. Transfer a fraction of that Asset to B and C
4. Generate and overspend transaction from B to C (make sure it fails)
5. With transaction from 4 generate a dryrunrequest and save the `msgp` file
6. Use `tealdbg` to debug the transaction

### Expected behaviour
Debugger should work.

### Actual behaviour
Debugger shows the following error:

```
2022/04/22 20:37:54 Decoding as JSON DryrunRequest object failed: json decode error [pos 1]: only encoded map or array can be decoded into a struct
2022/04/22 20:37:54 Debug error: msgpack decode error [pos 3662]: cannot decode unsigned integer: unrecognized descriptor byte: cb/float
```

Below you can find an example obtained with that procedure:

[example.zip](https://github.com/algorand/js-algorand-sdk/files/8544040/example.zip)

**Comment by barnjamin** [comment]
Did you already try setting the client to use `bigint`? 

https://algorand.github.io/js-algorand-sdk/classes/Algodv2.html#setIntEncoding

**Comment by rlora** [comment]
@barnjamin it works! Thanks a lot for pointing us in the right direction.

We're currently using `mixed` because we found out that using exclusively `bigint` would require some refactor that we will eventually do.

Thanks again, closing the issue.
