### ISSUE TITLE
Web Based apps no longer can decode the notes field

### ISSUE THREAD

**Issue by JasonWeathersby** [algorand/js-algorand-sdk#56]
With the msgpack replacement, using the decode function does not work in a web app. It does work in a node app though.

**Comment by rotemh** [comment]
General comments if someone gets to work on it before I do. 
The failure occurs because browserify fails to process the msgpack lib properly. Until browserify gets fixed, a workaround can be to simply merge msgpack's minified version to algosdk's minified one AFTER the browersify step.

**Comment by rotemh** [comment]
Fix - #71
