### ISSUE TITLE
Typechecking on `assetMetadataHash` possibly wrong

### ISSUE THREAD

**Issue by RamonBeast** [algorand/js-algorand-sdk#563]
### Subject of the issue

There might be a validation issue on the `assetMetadataHash` parameter for `makeAssetCreateTxnWithSuggestedParams()` (I haven't tested it with other functions.

Documentation says:

> Uint8Array or UTF-8 string representation of a hash commitment with respect to the asset. Must be exactly 32 bytes long.

In string format 32 bytes are the length of an MD5 hash, but what if someone wants to use a stronger algorithm, such as SHA256? Then using the `Uint8Array` form should work, only it doesn't:

```
   const assetMetadataHash : Uint8Array = createHash("sha256").update("metadata").digest(); // This returns a 32-bytes long Uint8Array

   // The assertion makes sure we have what we need
   assert(assetMetadataHash.length === 32 && assetMetadataHash instanceof Uint8Array);
```

At runtime I get an error (note that the assertion is successful):

```
Error: assetMetadataHash must be a 32 byte Uint8Array or string.
    at new Transaction (/src/transaction.js:230:23)
    at Object.makeAssetCreateTxnWithSuggestedParams (/src/makeTxn.js:167:12)
```

### Your environment

I'm using js SDK 1.15.0 with typescript

**Comment by kieranroneill** [comment]
I have also run into this problem. I think it is related to TypeScript. As you can see here: https://github.com/algorand/js-algorand-sdk/blob/642a2a0bda0f50d74d051ab0964c5a13e072f2f9/src/transaction.ts#L429 there is a strict check for a `Uint8Array`, but, like your example, I am passing a `Buffer`.

I haven't checked yet, but I think you need to explicitly pass a `Uint8Array`.

**Comment by kieranroneill** [comment]
Just had a go and wrapping the hash in `Uint8Array` seems to be accepted. Try:
```
const assetMetadataHash : Uint8Array = new Uint8Array(createHash("sha256").update("metadata").digest());
```

**Comment by RamonBeast** [comment]
Wrapping does the job, thanks a lot for your suggestion!
