### ISSUE TITLE
Logic Signature not Created from bytes array

### ISSUE THREAD

**Issue by HaseebK1** [algorand/js-algorand-sdk#579]
### Cannot Create Logic Signature From Bytes

I am using algosdk to create a group transaction, and one transaction i need to use a logic signature to sign the transaction with.
I am saving the bytes array of the compiled logic code and trying to use that uint8array to logic signature but I am consistently getting an error Extra 14 of 15 byte(s) found at buffer[1]

 const program = new Uint8Array(Buffer.from("KI4DJG2OOFJGUERJGSWCYGFZWDNEU2KWTU56VRJHITP62PLJ5VYMBFDBFE" , "base64"));
let assetTransferLogicSignatue = algosdk.logicSigFromByte(program)

**Comment by jasonpaulos** [comment]
Hi @HaseebK1, there are two things that seem wrong.
1. `KI4DJG2OOFJGUERJGSWCYGFZWDNEU2KWTU56VRJHITP62PLJ5VYMBFDBFE` seems to be an address, not a compiled LogicSig
2. If you have a compiled LogicSig, the best way to use it is to create a [`LogicSigAccount`](https://algorand.github.io/js-algorand-sdk/classes/LogicSigAccount.html) object with it. This can be created with a simple constructor call, e.g. `new LogicSigAccount(uint8array_of_compiled_program)`. Once you have this, you can use [`signLogicSigTransaction`](https://algorand.github.io/js-algorand-sdk/modules.html#signLogicSigTransaction) to have that program sign a transaction.

The method you are using, `logicSigFromByte`, is meant for decoding a msgpack encoded LogicSig program + signatures, which I don't think is what you want.
