### ISSUE TITLE
HTTPS Support on API

### ISSUE THREAD

**Issue by JasonWeathersby** [algorand/js-algorand-sdk#61]
Currently, most web apps will be deployed as HTTPS, which prevents calling HTTP REST calls. If we are not going to implement HTTPS on our REST calls What is the suggestion for handling this? Proxy? Looking for something I can document on our developer site. Many Hackathon users are having this issue.

**Comment by ian-algorand** [comment]
Adding this to the FDE board to be triaged

**Comment by rotemh** [comment]
That's somewhat orthogonal to our work. The easy way is to setup a reverse proxy with Nginx or something similar.

**Comment by ian-algorand** [comment]
If we go with the proxy route, any chance you'd be able to help @JasonWeathersby set that up? I just want to make sure we don't hit a dead end here.

**Comment by rotemh** [comment]
What do you mean? there is a need to do that to every node we want to put behind HTTPS

**Comment by JasonWeathersby** [comment]
I understand this one. I was looking for a good suggestion for our users

**Comment by rotemh** [comment]
I use reverse proxy with nginx and let's encrypt with my https nodes. it takes about 10 minutes to setup.

**Comment by JasonWeathersby** [comment]
That works Rotem
