### ISSUE TITLE
Skip preflight queries for API endpoints with no tokens

### ISSUE THREAD

**Issue by urtho** [algorand/js-algorand-sdk#635]
## Problem

Any usage of custom headers in HTTP requests causes browsers to send extra preflight query.
This makes no sense in case of empty token and can be avoided by not sending the header at all.

## Solution

Do not attach 'X-Indexer-API-Token' | 'X-KMD-API-Token' | 'X-Algo-API-Token' if case of empty header value.

**Comment by urtho** [comment]
Thought this would make it into v2.0.0 :'(

**Comment by Eric-Warehime** [comment]
@urtho 

It seems like there's maybe two different types of issues here:

1. Algod and Kmd both require a token for almost all of their APIs (except for things like `/versions`, /health`, `/ready`, etc). As far as I know you can't run these APIs without an authenticator which checks a provided token.

 We could mark certain endpoints as part of the set of [common APIs](https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/server/common/routes.go#L24) and avoid sending the headers for these endpoints.


2. It's possible to run an indexer without auth, by not providing the [tokenString](https://github.com/algorand/indexer/blob/develop/cmd/algorand-indexer/daemon.go#L304). In this case you probably wouldn't want to send the header ever.

Are you interested in both of these cases or just one in particular?

**Comment by urtho** [comment]
My use case is only for front-end apps where token (client side) is assigned an empty value ('', null, undefined) in the config. 
My ask is to not send a token header (indexer & algod) at all in this and only this case.

So I am interested in 1&2 - but they do not require a grouping APIs as the token is empty (client side) either way.
This should not break things as not sending a header vs sending one with empty value is of no consequence to algod / indexer.

Providers hide algod/indexer behind gateways that can choose to do different auth mech - like JWT or URL based tokens.
Anything but a custom header that triggers preflight for each request doubling the response latency.

**Comment by Eric-Warehime** [comment]
PR #782 is merged. It should go out in the next SDK release (sometime in the next couple of weeks I'd guess?). Feel free to re-open this if you pick up this change and it doesn't work for you.
