### ISSUE TITLE
Allow manually adding foreign refs to transactions generated with `addMethodCall`

### ISSUE THREAD

**Issue by barnjamin** [algorand/js-algorand-sdk#653]
In the case that a foreign ref (asset,acct,app) is not specified in the method signature but might be needed for some reason, the caller of the `AtomicTransactionComposer.addMethodCall` should still be able to provide it

**Comment by ErikHasselwander** [comment]
I just want to add that this is a much needed feature, and the python SDK already has it. The workaround for this is very disruptive and requires you to break out of the ATC with `AtomicTransactionComposer.buildGroup()`.

**Comment by barnjamin** [comment]
Re-upping this one 🙏

**Comment by rocalex** [comment]
Same issue

**Comment by ultrade-dev** [comment]
Guys can we please get this fixed?
It's disrupting our work.
