### ISSUE TITLE
Add wrappers to main.js and update README with examples

### ISSUE THREAD

**Issue by rotemh** [algorand/js-algorand-sdk#69]

**Comment by EvanJRichard** [comment]
plan: inspired by go-sdk, do something like
`MakePayTxn`, `MakeKeyRegTxn`, `MakeAssetConfigTxn`, `MakeAssetDestroyTxn`, (Create?), `MakeAssetTransferTxn`, `MakeAssetRevokeTxn`, `MakeAssetFreezeTxn` and add examples to `README`

- [ ] `MakePayTxn`
- [ ] `MakeKeyRegTxn`
- [ ] `MakeAssetConfigTxn`
- [ ] `MakeAssetDestroyTxn`
- [ ] `MakeAssetTransferTxn`
- [ ] `MakeAssetRevokeTxn` 
- [ ] `MakeAssetFreezeTxn`
- [ ] `README.md`
