### ISSUE TITLE
logicSigFromByte not working when using LogicSigAccount

### ISSUE THREAD

**Issue by FernandoViudez** [algorand/js-algorand-sdk#695]
I built a logic sig using the following code:

```
// after compile, result.result
const program = "BSADAQAwMwAQIhJEMwAIgegHEkQzAAAxABJEMwAHgCBErzMp0f77vnUU8n1n0V3A258hcIh8DL0aknn61MBdghJEMwAgMgMSRDMACTIDEkQzARCBAxJEMwERNhoAiABaEkQzASoyAxNEMwEpgCDadZUKto6y1PaRkwQ1ybyyHYDjwlF16i4jS8j869Nd3RJEMwEgMgMSRDMBFTIDEkQiQzUBgQo0AZSJNQI0AiQPRDQCgTkORDQCJAmJNQA0ABUjDUAABCNCACE0ACNViP/ZNAAVIgmI/8kLNAAiNAAVUjQATIj/1Uw1AAiJ"

const logicSig = new LogicSigAccount(
    new Uint8Array(Buffer.from(program, 'base64')),
    [encodeUint64(1)], // example arg
);
const b64logicSig = Buffer.from(logicSig.toByte()).toString("base64")

// when recovering at back, i.e.
const bytes = new Uint8Array(Buffer.from(b64logicSig, "base64"))
const arg = logicSigFromByte(bytes).args[0];
console.log(decodeUint64(arg));
```

I got "empty program" error that comes from `logicSigFromByte` method.

If i change the method for create Logic sig and use `makeLogicSig` instead, this works fine.

As far i know, the main problem here is that you can't recover a logic sig from b64 when creating from `new LogicSigAccount(...)`

**Comment by jasonpaulos** [comment]
`LogicSigAccount.fromByte` can be used to decode an encoded `LogicSigAccount`.

`logicSigFromByte` is only meant to decode encoded `LogicSig` objects.

I hope that helps.
