### ISSUE TITLE
algosdk.getApplicationAddress() no longer works due to buf.writeBigUint64BE being undefined

### ISSUE THREAD

**Issue by headline-design** [algorand/js-algorand-sdk#722]
Have used this function reliably over the past year with no issues. Suddenly stopped working on Chrome and Firefox.

**Comment by headline-design** [comment]
Added PR - https://github.com/algorand/js-algorand-sdk/pull/730#issue-1525790115

**Comment by jasonpaulos** [comment]
Fixed by #733
