### ISSUE TITLE
msgpack decodeObj error for certain note data

### ISSUE THREAD

**Issue by haardikk21** [algorand/js-algorand-sdk#75]
In Algorand testnet, various blocks including, but not limited to, round 2728533 to round 2729468 seem to contain transactions with note fields such that `algosdk.decodeObj(transaction.note)` returns a `RangeError: Extra 15 bytes located in buffer[1]` 

I tried using the note field from the same blocks and transactions using the Go SDK and the error didn't show up.

**Comment by EvanJRichard** [comment]
More context from haardikk21:
>FWIW; doing `Buffer.from(transaction.noteb64, 'base64').toString()` worked for the problematic blocks. But when using that solution for transactions I had created where the note field was just a string, for some reason it would add an extra random character before the actual string I put in

>Based on a quick overview, I don't think it's related to issue #56. I did try importing `msgpack` myself and doing what `algod` does under the hood for `decodeObj` and the error still persisted. maybe msgpack needs to be updated?

**Comment by EvanJRichard** [comment]
@haardikk21 For additional context, can you please share a transaction whose note exhibits this behavior? And, was that note encoded using `msgpack`, too? Thanks! 🙇

**Comment by haardikk21** [comment]
> @haardikk21 For additional context, can you please share a transaction whose note exhibits this behavior? And, was that note encoded using `msgpack`, too? Thanks!

Here's an example: https://testnet.algoexplorer.io/tx/J7EDHHV6FGNITHRP5RKNKOMIPNXQUISEQ6VCPJL5KXKDWT7RPCMA
Decoding this note fails with the JS SDK, but is fine with the Go SDK.
I'm not sure how this note was encoded as I'm not the creator of this transaction, however my application requires being able to iterate over all blocks and all transactions and filter out the ones which have relevant note fields -- which I can't do if it throws an error.

**Comment by haardikk21** [comment]
Replacing `algosdk.decodeObj(...)` with `msgpack.deserialize(transaction.note).toString()` worked when using the msgpack library over at https://github.com/ygoe/msgpack.js

Something seems to be wrong with `msgpack-javascript`

**Comment by fionnachan** [comment]
Just encountered the same issue :/
`algosdk.decodeObj(Buffer.from(transaction.note, "base64"))` gives me this error 
```
Uncaught RangeError: Extra 7 of 8 byte(s) found at buffer[1]
    at e.createNoExtraBytesError (algosdk.min.js:3)
    at e.doDecodeSingleSync (algosdk.min.js:3)
    at e.decode (algosdk.min.js:3)
    at Module.H (algosdk.min.js:3)
    at Module.s (algosdk.min.js:3)
    at Module.j (algosdk.min.js:3)
```
but `msgpack.deserialize(Buffer.from(transaction.note, "base64"))` works perfectly.

Other than that, I also tried another package https://www.npmjs.com/package/@msgpack/msgpack which gave the same error.
