### ISSUE TITLE
Insecure dependencies are used: need to upgrade to better ones

### ISSUE THREAD

**Issue by paulmillr** [algorand/js-algorand-sdk#777]
You are using following dependencies:

```
    "hi-base32": "^0.5.1",
    "js-sha256": "^0.9.0",
    "js-sha3": "^0.8.0",
    "js-sha512": "^0.8.0",
    "tweetnacl": "^1.0.3",
```

They are not secure. I suggest to upgrade to noble-hashes and noble-curves, which are modern, audited, support ESM+Common.js and a bunch of other stuff. The noble libraries are used all over Ethereum and Solana ecosystems already.

**Comment by Eric-Warehime** [comment]
Thanks, you've already opened a similar issue in #742 We are taking a look at some of our older dependencies and figuring out if a migration is worthwhile. I'll close this in favor of looking at the issue in 742.
