### ISSUE TITLE
Bad error message when passing transaction as ABI method argument

### ISSUE THREAD

**Issue by acfunk** [algorand/js-algorand-sdk#781]
https://github.com/algorand/js-algorand-sdk/blob/d235e6882e8fdc5a67989387f66beff635a4f3e0/src/composer.ts#L348-L356

The error message should indicate `TransactionWithSigner` of the correct type is expected, not just `Transaction` of the correct type.

**Comment by Eric-Warehime** [comment]
Merged in #780 Will be released in the next release.
