### ISSUE TITLE
Wrong transaction ID

### ISSUE THREAD

**Issue by oliviera9** [algorand/js-algorand-sdk#792]
### Wrong transaction ID from payment transaction

I have this [transaction](https://goalseeker.purestake.io/algorand/mainnet/transaction/JOSKWFOAUVOYCMRTGBKV6L5U767WA4UHD5XERYSUNCC2QP7I5NGQ) which I cannot replicate from the SDK: in particular, the resulting ID is different.

### Your environment

* Software version: `algosdk 2.3.0, node v16.15.1`

### Steps to reproduce
```js
const algosdk = require('algosdk');
const suggestedParams = {
        fee: 1000,
        firstRound: 29285108,
        lastRound: 29286108,
        genesisHash: 'wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=',
        genesisID: 'mainnet-v1.0',
    }
const a = new algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        from: 'X5SKLROIIFMUJWB6HS4AD3YJ7OQGBFNCFBJ2HGGGFFBX3M62ZECVX7I2WE',
        to: 'XNFT36FUCFRR6CK675FW4BEBCCCOJ4HOSMGCN6J2W6ZMB34KM2ENTNQCP4',
        suggestedParams,
        amount: 0,
        closeRemainderTo: 'XNFT36FUCFRR6CK675FW4BEBCCCOJ4HOSMGCN6J2W6ZMB34KM2ENTNQCP4',
        note: new Uint8Array()
    })
a.group = 'uuWEqwPI7c/tWT1YDqyEdjCyfkuw1WILO4f9+XSi/8Y='
a.fee = 1000
console.info('ID', a.txID())
```

### Expected behaviour
Output should be `JOSKWFOAUVOYCMRTGBKV6L5U767WA4UHD5XERYSUNCC2QP7I5NGQ`

### Actual behaviour
`R4IS6ZFVO5OXZT2IIMFYIT2V4HQY27ERLC7WOFM77KMHISU5GD7Q`

**Comment by jasonpaulos** [comment]
@oliviera9 the group property is supposed to be a `Buffer`, not a string. When I changed that line to this, I got the correct result, `JOSKWFOAUVOYCMRTGBKV6L5U767WA4UHD5XERYSUNCC2QP7I5NGQ`:

```javascript
a.group = Buffer.from('uuWEqwPI7c/tWT1YDqyEdjCyfkuw1WILO4f9+XSi/8Y=', 'base64');
```

(and note, you don't need `new` when calling `algosdk.makePaymentTxnWithSuggestedParamsFromObject`)
