### ISSUE TITLE
Add array length check to encodeAddress

### ISSUE THREAD

**Issue by winder** [algorand/js-algorand-sdk#805]
### Subject of the issue

The `encodeAddress` function should check array length before it begins to generate a response. The current implementation would return strange results if the wrong sized array were used. It isn't clear if applications could be depending on this behavior, so we should fix it in the 3.0.0 release.

https://github.com/algorand/js-algorand-sdk/blob/4e1073d6a15b443a73dedf42b025173b397624b0/src/encoding/address.ts#L103

**Comment by algochoi** [comment]
Closed by #809
