### ISSUE TITLE
[Research] Make transaction objects consistent

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/js-algorand-sdk#81]
Maybe relates to #70. There's been a class of bugs/UX-problems users and dev-rel have been experiencing: some functions expect arguments to pass to a `Transaction` constructor, some functions expect an already-constructed `Transaction`, and it's not clear which are which.

For example: `main.js:signTransaction(txn, sk)` expects `txn` to be a dictionary of arguments. However, the `main.js:make[VariousKindsOf]Transaction` functions return an object, not a dictionary of arguments. So, this type of pseudocode would error, which seems to surprise developers:
```
let txn = makeAssetCreateTxn(arguments, arguments, arguments, etc.)
let signedTxn  = signTransaction(txn, sk) //errors. developers should use txn.signTxn(sk) instead.
```

Possible solution: Add constructor from Transaction object to Transaction object, so that when the Transaction constructor unexpectedly receives another Transaction, rather than a dictionary of args, the result is not an error.
Possible solution: This might be fixable with better documentation/a different design. There's nothing actually broken here, the problem is that people get surprised when certain functions don't work together. For example, I'm now noticing that `main.js:signTransaction`, which expects `txn` to be a dictionary of arguments, says it expects `@param txn object with either payment or key registration fields` which makes it sound like it needs a `Transaction object`.

**Comment by aquabu** [comment]
Yup. I can confirm this is not obvious and not well documented ;-)

Several examples of `makeAssetTransferTxn` in the [docs](https://github.com/algorand/js-algorand-sdk) imply the transaction should be signed without showing the code to do it. So it's not clear that the correct way to sign is`txn.signTxn(sender.sk)` Here's an example from the README:

<img width="824" alt="Screen Shot 2020-02-03 at 6 02 47 PM" src="https://user-images.githubusercontent.com/7595/73707117-68d17500-46af-11ea-84d8-7fe7970313a6.png">

The failure message when you encounter this is "address seems to be malformed" which doesn't help clarify that the failure is from using `algosdk.signTransaction(txn, sender.sk)`
