### ISSUE TITLE
atc.gatherSignatures() failing with Multisig

### ISSUE THREAD

**Issue by acfunk** [algorand/js-algorand-sdk#821]
### atc.gatherSignatures() failing with Multisig

When gathering signatures for an AtomicTransactionComposer group with a multisig transaction, the following error is thrown:

`Not enough multisig transactions to merge. Need at least two`

### Your environment

algosdk 2.5.0

### Steps to reproduce

1. Create an ATC with one or more `TransactionWithSigner`s that have a MultiSig signer
2. `const signedTxns = await atc.gatherSignatures()`

### Expected behaviour
`signedTxns` contains signed transactions
### Actual behaviour
error is thrown `Not enough multisig transactions to merge. Need at least two`

**Comment by winder** [comment]
Are you using a multisig that only requires one signature?

**Comment by acfunk** [comment]
Yes, it's a 1 of 2 multi-sig. I started looking into the problem and realized that was a factor. Sorry it wasn't in the repro steps.

I figure something like this in place of this line would fix it...

https://github.com/algorand/js-algorand-sdk/blob/7469c41ab4a54dec44a9ee55da57d54bafd444be/src/signer.ts#L76

      if(partialSigs.length > 1) {
        signed.push(mergeMultisigTransactions(partialSigs));
      } else {
        signed.push(partialSigs[0]);
      }

**Comment by winder** [comment]
@acfunk thanks, that sounds right to me as well. Would you like to make a PR?

**Comment by acfunk** [comment]
@winder I was going to, but I couldn't figure out how to test it locally. Editing the file in node_modules had no effect - too much optimization by Vite it seems. And I'd feel bad submitting a PR that I hadn't tested... unless you told me to.

**Comment by winder** [comment]
@algochoi could you provide some testing guidance here?

**Comment by algochoi** [comment]
We could have a mocha unit test here: https://github.com/algorand/js-algorand-sdk/blob/develop/tests/10.ABI.ts 

something like:
```
it('should accept at least one signature in the multisig', () => {
// ...
});
```

**Comment by acfunk** [comment]
I submitted a PR #822
