### ISSUE TITLE
Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by nullun** [algorand/js-algorand-sdk#823]
### Subject of the issue

Since algosdk v2.5.0 a [sample svelte project](https://github.com/nullun/vite-svelte-algorand) I have now breaks when built and served from a web server, giving the following error message in the console when the page loads.
`Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation`

A little digging reveals that it is https://github.com/algorand/js-algorand-sdk/pull/794 which causes the issue, and so I believe it's to do with cross-fetch being polyfilled?

The code works if I run `npm run dev` locally in a development environment, it's only broken when I do `npm run build` and serve the dist folder from a web server. The project is currently [deployed](https://vite-svelte-algorand.netlify.app/) using v2.4.0 and it's working as expected, but I'm unable to update to 2.5.0 due to the cross-fetch update.

### Your environment

macOS 13.5.1
node v20.5.1
npm 9.8.0

### Steps to reproduce

1. `git clone git@github.com:nullun/vite-svelte-algorand.git`
2. `cd vite-svelte-algorand`
3. `npm install`
4. `npm run build`
5. Host the `dist` folder on a webserver, I use apache2 locally and have `~/Sites` set to `127.0.0.1/~nullun/`. So I would do something like `ln -s ~/vite-svelte-algorand/dist ~/Sites/dist`
6. Visit http://127.0.0.1/~nullun/dist/ or whatever your destination is

### Expected behaviour

The page loads without errors, showing the latest Algorand Mainnet round.

### Actual behaviour

Page loads with an error, preventing retrieval of latest Algorand Mainnet round.

**Comment by acfunk** [comment]
Having the exact same issue with Vue/Vite.

**Comment by spencercap** [comment]
Same

**Comment by spencercap** [comment]
in the vue + vite env, what's strange is that this only happens when trying to make async calls from algosdk after a build (`vite build` followed by a `vite preview`), and NOT while running a dev server (`vite serve`)

also, `algosdk@v2.4.0` does not experience this bug.

**Comment by SilentRhetoric** [comment]
Will this be fixed in v3.0 (or sooner)?

**Comment by scholtz** [comment]
i have the same issue.. https://vue-illegal-invocation.vercel.app/

source code is quite simple: https://github.com/scholtz/vue-illegal-invocation/blob/main/src/App.vue

please prioritize the release of the fix pls

**Comment by jasonpaulos** [comment]
Hi all, this was just released in v2.7.0.
