### ISSUE TITLE
Add ability to pass in fetch options for urlTokenBaseHTTPClient requests

### ISSUE THREAD

**Issue by PhearZero** [algorand/js-algorand-sdk#858]
## Problem

There is no way to abort the execution of a `fetch` request mid-flight. There is limited access to the fetch options and it is currently not possible to set the `signal` key to an `AbortSignal` from an `AbortController`.

- https://developer.mozilla.org/en-US/docs/Web/API/AbortController

## Solution

Allow for all additional options to be passed to the fetch client. This will also solve any future use cases that rely on access to the `fetch` options.

```javascript
client.getSomeRequest().do( headers, {signal} )
```

## Urgency

Very low

**Comment by jasonpaulos** [comment]
Good suggestion. I'll add this to the issues to be considered for v3

**Comment by jasonpaulos** [comment]
Closed by #883
