### ISSUE TITLE
Error when trying to run Hello World sample app 

### ISSUE THREAD

**Issue by mvieiradcu** [algorand/js-algorand-sdk#865]
### Subject of the issue
Error when running Hello World Sample App With Front-End 

I am trying to run the sample app Hello World using the command `almost init`. After executing the smart contract, build and deploy. When running the Front-End application, I am getting the error. 

I was trying to follow this video - https://www.youtube.com/watch?v=4-Xy6svMH04&t=609s

```
node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'set-blocking'
Require stack:
- /Users/mv/.npm/_npx/81881/lib/node_modules/generate/bin/generate.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at process.<anonymous> (/Users/mv/.npm/_npx/81881/lib/node_modules/generate/bin/generate.js:5:3)
    at process.emit (node:events:531:35) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mv/.npm/_npx/81881/lib/node_modules/generate/bin/generate.js'
  ]
}

Node.js v21.7.1

Client generation failed for /Users/mv/Desktop/algorand-simple-app/algorand-test/projects/algorand-test-contracts/smart_contracts/artifacts/hello_world/application.json.
```

### Your environment
* Algokit version - algokit, version 2.0.2
* goal status 
      `
      algokit goal node status
       Last committed block: 3
       Time since last block: 2297.6s
       Sync Time: 0.0s
       Last consensus protocol: future
       Next consensus protocol: future
       Round for next consensus protocol: 4
       Next consensus protocol supported: true
       Last Catchpoint:
       Genesis ID: dockernet-v1
       Genesis hash: YzNbyoDyOjncaJ0uZ6zFAdd8U9SJGe/xZqBgo+0E0Wc=
      `
* MacOS Sonoma 14.2.1

### Steps to reproduce

1. Algokit init
2.  Selected these options 
```
          ? Which of these options best describes the project you want to build? Smart Contracts & DApp Frontend 🎛️
          ? Which language would you like to use for the smart contract? PyTeal 🔧
          ? Name of project / directory to create the project in: algorand-test
          Starting template copy and render at /Users/marciovieira/Desktop/algorand-simple-app/algorand-test...
          🎤 Name of the template preset to use.
             Starter - for a simpler starting point ideal for prototyping
          🎤 Name of the default smart contract app.
             hello_world
          🎤 Pick language for deployment scripts in the backend?
             Python
          ==== Checking compatibility with the cli ===
```
3.  Build and Deploy the smart contract using the script on launch.json file 
4. Trying to execute `npm run dev` command.

**Comment by jasonpaulos** [comment]
Hi @mvieiradcu, this appears to be an algokit issue, not a problem directly with the JS Algorand SDK. For that reason, I'm going to close this, and I strongly recommend opening this issue in https://github.com/algorandfoundation/algokit-cli

**Comment by mvieiradcu** [comment]
Thanks, @jasonpaulos. I created the issue on algokit-cli. I am adding the link just for future reference.
https://github.com/algorandfoundation/algokit-cli/issues/473
