### ISSUE TITLE
Inquiry on 2.9.0 release 

### ISSUE THREAD

**Issue by aorumbayev** [algorand/js-algorand-sdk#879]
### Subject of the issue

ABIMethodParams with latest changes in https://github.com/algorand/js-algorand-sdk/blob/7f2e7340b86059a8bfca4e237af663c71c577da7/src/abi/method.ts#L66 now contains optional readonly field. Puya compiler is also updated to support generation of app specs with this field defined. However given that the changes aren't propagetd to npm yet, latest 2.8.0 would yield in faulty algokit typed clients (which refer to older ABIMethodParams definition, which does not contain the `readonly` field). 

Is there an approximate release date on when the latest from develop is going to be propagated under next version to npm (2.9.0 i assume?). If the release date is a later date we can introduce a patch on algokit repos side, propagating the latest changes from develop however would have been the simplest as we don't pin algosdk peer dependency version (unless there are other major changes on develop that are blocking from propagating the latest).

**Comment by jasonpaulos** [comment]
2.9.0 has just been released
